/* ═══════════════════════════════════════════════════════════════
   DALE ESPAÑOL — CURRICULUM DATA
   Formal Track: A1→C2 (74 lessons total when complete)
   Venezuelan Track: Vz1→Vz5 (28 lessons total when complete)
   Currently loaded: A1 (12 lessons). Adding A2/B1/B2/C1/C2/Vz next.
   ═══════════════════════════════════════════════════════════════ */

/* Assigns to window.CURRICULUM so app.jsx can read it without ES module imports.
   Works with raw file GitHub Pages deployment — no build step needed. */

window.CURRICULUM = window.CURRICULUM || {};

window.CURRICULUM.LEVELS = [
  { id: "A1", name: "Principiante", color: "#22c55e", desc: "Foundations" },
  { id: "A2", name: "Elemental", color: "#f0a500", desc: "Past tenses & pronouns" },
  { id: "B1", name: "Intermedio", color: "#3b82f6", desc: "Subjunctive & complex tenses" },
  { id: "B2", name: "Avanzado", color: "#a855f7", desc: "Mastery of all moods" },
  { id: "C1", name: "Superior", color: "#ec4899", desc: "Native-level nuance" },
  { id: "C2", name: "Maestría", color: "#ef4444", desc: "Mastery" }
];

window.CURRICULUM.VZ_LEVELS = [
  { id: "Vz1", name: "Básico", color: "#06b6d4" },
  { id: "Vz2", name: "Elemental", color: "#0891b2" },
  { id: "Vz3", name: "Intermedio", color: "#0e7490" },
  { id: "Vz4", name: "Avanzado", color: "#155e75" },
  { id: "Vz5", name: "Maestría", color: "#164e63" }
];

// ─── REFERENCE TAB DATA ───────────────────────────────────────────
window.CURRICULUM.REFERENCE = {
  conjugations: [
    { title: "Present Tense Regular", verbs: [
      { inf: "hablar (-AR) — to speak", forms: ["hablo","hablas","habla","hablamos","hablan"] },
      { inf: "comer (-ER) — to eat", forms: ["como","comes","come","comemos","comen"] },
      { inf: "vivir (-IR) — to live", forms: ["vivo","vives","vive","vivimos","viven"] }
    ]},
    { title: "Present Tense — Common Irregulars", verbs: [
      { inf: "ser — to be (identity)", forms: ["soy","eres","es","somos","son"] },
      { inf: "estar — to be (state)", forms: ["estoy","estás","está","estamos","están"] },
      { inf: "ir — to go", forms: ["voy","vas","va","vamos","van"] },
      { inf: "tener — to have", forms: ["tengo","tienes","tiene","tenemos","tienen"] },
      { inf: "hacer — to do/make", forms: ["hago","haces","hace","hacemos","hacen"] },
      { inf: "querer — to want", forms: ["quiero","quieres","quiere","queremos","quieren"] },
      { inf: "poder — to be able", forms: ["puedo","puedes","puede","podemos","pueden"] },
      { inf: "decir — to say", forms: ["digo","dices","dice","decimos","dicen"] },
      { inf: "ver — to see", forms: ["veo","ves","ve","vemos","ven"] },
      { inf: "saber — to know facts", forms: ["sé","sabes","sabe","sabemos","saben"] },
      { inf: "venir — to come", forms: ["vengo","vienes","viene","venimos","vienen"] },
      { inf: "dar — to give", forms: ["doy","das","da","damos","dan"] }
    ]},
    { title: "Preterite Regular", verbs: [
      { inf: "hablar (-AR)", forms: ["hablé","hablaste","habló","hablamos","hablaron"] },
      { inf: "comer (-ER)", forms: ["comí","comiste","comió","comimos","comieron"] },
      { inf: "vivir (-IR)", forms: ["viví","viviste","vivió","vivimos","vivieron"] }
    ]},
    { title: "Preterite Irregular — Big 6", verbs: [
      { inf: "ir / ser → fui", forms: ["fui","fuiste","fue","fuimos","fueron"] },
      { inf: "tener → tuv-", forms: ["tuve","tuviste","tuvo","tuvimos","tuvieron"] },
      { inf: "hacer → hic-/hiz-", forms: ["hice","hiciste","hizo","hicimos","hicieron"] },
      { inf: "poder → pud-", forms: ["pude","pudiste","pudo","pudimos","pudieron"] },
      { inf: "decir → dij-", forms: ["dije","dijiste","dijo","dijimos","dijeron"] },
      { inf: "venir → vin-", forms: ["vine","viniste","vino","vinimos","vinieron"] }
    ]},
    { title: "Imperfect Tense", verbs: [
      { inf: "hablar (-AR)", forms: ["hablaba","hablabas","hablaba","hablábamos","hablaban"] },
      { inf: "comer (-ER)", forms: ["comía","comías","comía","comíamos","comían"] },
      { inf: "vivir (-IR)", forms: ["vivía","vivías","vivía","vivíamos","vivían"] },
      { inf: "ir (irreg)", forms: ["iba","ibas","iba","íbamos","iban"] },
      { inf: "ser (irreg)", forms: ["era","eras","era","éramos","eran"] },
      { inf: "ver (irreg)", forms: ["veía","veías","veía","veíamos","veían"] }
    ]},
    { title: "Future Tense", verbs: [
      { inf: "hablar (regular)", forms: ["hablaré","hablarás","hablará","hablaremos","hablarán"] },
      { inf: "tener (irreg)", forms: ["tendré","tendrás","tendrá","tendremos","tendrán"] },
      { inf: "hacer (irreg)", forms: ["haré","harás","hará","haremos","harán"] },
      { inf: "poder (irreg)", forms: ["podré","podrás","podrá","podremos","podrán"] },
      { inf: "decir (irreg)", forms: ["diré","dirás","dirá","diremos","dirán"] },
      { inf: "venir (irreg)", forms: ["vendré","vendrás","vendrá","vendremos","vendrán"] }
    ]},
    { title: "Conditional Tense", verbs: [
      { inf: "hablar (regular)", forms: ["hablaría","hablarías","hablaría","hablaríamos","hablarían"] },
      { inf: "tener (irreg)", forms: ["tendría","tendrías","tendría","tendríamos","tendrían"] },
      { inf: "hacer (irreg)", forms: ["haría","harías","haría","haríamos","harían"] }
    ]},
    { title: "Present Subjunctive", verbs: [
      { inf: "hablar (-AR)", forms: ["hable","hables","hable","hablemos","hablen"] },
      { inf: "comer (-ER)", forms: ["coma","comas","coma","comamos","coman"] },
      { inf: "vivir (-IR)", forms: ["viva","vivas","viva","vivamos","vivan"] },
      { inf: "ser (irreg)", forms: ["sea","seas","sea","seamos","sean"] },
      { inf: "estar (irreg)", forms: ["esté","estés","esté","estemos","estén"] },
      { inf: "ir (irreg)", forms: ["vaya","vayas","vaya","vayamos","vayan"] },
      { inf: "saber (irreg)", forms: ["sepa","sepas","sepa","sepamos","sepan"] },
      { inf: "haber (irreg)", forms: ["haya","hayas","haya","hayamos","hayan"] }
    ]},
    { title: "Imperfect Subjunctive (-ra form)", verbs: [
      { inf: "hablar", forms: ["hablara","hablaras","hablara","habláramos","hablaran"] },
      { inf: "comer", forms: ["comiera","comieras","comiera","comiéramos","comieran"] },
      { inf: "ser/ir", forms: ["fuera","fueras","fuera","fuéramos","fueran"] },
      { inf: "tener", forms: ["tuviera","tuvieras","tuviera","tuviéramos","tuvieran"] }
    ]},
    { title: "Present Perfect", verbs: [
      { inf: "haber (auxiliary)", forms: ["he","has","ha","hemos","han"] },
      { inf: "Past participles", forms: ["hablado","comido","vivido","hecho","dicho"] }
    ]},
    { title: "Imperative (Commands)", verbs: [
      { inf: "hablar — tú affirmative", forms: ["habla"] },
      { inf: "hablar — tú negative", forms: ["no hables"] },
      { inf: "hablar — usted", forms: ["hable / no hable"] },
      { inf: "hablar — ustedes", forms: ["hablen / no hablen"] },
      { inf: "Irregular tú: haz, ven, pon, sal, ten, di, ve", forms: ["haz","ven","pon","sal","ten","di","ve"] }
    ]}
  ],
  pronouns: [
    { title: "Subject Pronouns", rows: [["yo","I"],["tú","you (informal)"],["usted","you (formal)"],["él/ella","he/she"],["nosotros","we"],["ustedes","you all (LATAM)"],["ellos/ellas","they"]] },
    { title: "Direct Object", rows: [["me","me"],["te","you"],["lo","him/it (m)"],["la","her/it (f)"],["nos","us"],["los","them (m)"],["las","them (f)"]] },
    { title: "Indirect Object", rows: [["me","to me"],["te","to you"],["le","to him/her/usted"],["nos","to us"],["les","to them/ustedes"]] },
    { title: "Reflexive", rows: [["me","myself"],["te","yourself"],["se","himself/herself/yourself"],["nos","ourselves"],["se","themselves/yourselves"]] },
    { title: "Prepositional", rows: [["mí","me (after prep)"],["ti","you"],["él/ella/usted","him/her/you"],["nosotros","us"],["ellos/ellas/ustedes","them/you all"]] }
  ],
  guides: [
    { title: "Ser vs Estar", content: "SER (permanent identity, characteristics, origin, time, profession):\n• Soy alta. (I am tall — characteristic)\n• Es de Venezuela. (She's from Venezuela — origin)\n• Son las tres. (It's three o'clock — time)\n• Es médica. (She's a doctor — profession)\n\nESTAR (location, temporary states, ongoing actions):\n• Estoy en casa. (I'm at home — location)\n• Está cansada. (She's tired — temporary state)\n• Estoy comiendo. (I'm eating — ongoing action)\n\nMeaning shifts:\n• Es aburrido = he is boring\n• Está aburrido = he is bored\n• Es listo = he is clever\n• Está listo = he is ready" },
    { title: "Por vs Para", content: "POR (cause, exchange, duration, by, through):\n• Por ti = because of you\n• Gracias por venir = thanks for coming\n• Por dos horas = for two hours\n• Hecho por ella = made by her\n• Caminamos por el parque = we walked through the park\n\nPARA (destination, purpose, recipient, deadline):\n• Para ti = for you (recipient)\n• Estudio para aprender = I study in order to learn\n• Para Madrid = toward Madrid\n• Para el lunes = by Monday\n• Es para mi mamá = it's for my mom" },
    { title: "Preterite vs Imperfect", content: "PRETERITE — Completed events. Specific times. Main story.\nTriggers: ayer, anoche, una vez, de repente, el lunes pasado.\n• Comí pizza ayer.\n• Llegó a las 8.\n\nIMPERFECT — Background, descriptions, habits, ongoing past.\nTriggers: siempre, nunca, todos los días, mientras, cuando era niño.\n• Comía pizza los viernes.\n• Era alta y tenía pelo rubio.\n\nMIXED — Imperfect sets scene; preterite delivers event.\n• Llovía cuando llegó. (It was raining when he arrived.)\n• Estaba cansada, así que me acosté." },
    { title: "Saber vs Conocer", content: "SABER — Know facts, info, how to do something.\n• Sé tu nombre.\n• Sé hablar español.\n• Sabe la respuesta.\n\nCONOCER — Know people, places, be familiar.\n• Conozco a María. (Personal a required for people.)\n• Conozco Caracas.\n• Conozco esa canción.\n\nIN PRETERITE:\n• Supe = I found out (moment of discovery)\n• Conocí = I met (first time)" },
    { title: "Subjunctive — When to Use (WEIRDO)", content: "W — Wishes/Wants: Quiero que vengas.\nE — Emotions: Me alegra que estés aquí.\nI — Impersonal expressions: Es importante que estudies.\nR — Recommendations: Sugiero que vayas.\nD — Doubt/Denial: Dudo que sea verdad.\nO — Ojalá: Ojalá llueva mañana.\n\nNon-existence: Busco a alguien que hable inglés.\n\nKey signal: \"que\" + change of subject often triggers subjunctive." },
    { title: "Accent Mark Rules", content: "Spanish tildes are NOT optional.\n\nDefault stress (no tilde):\n• Ends in vowel/n/s → stress on second-to-last syllable. (casa, comen)\n• Ends in other consonant → stress on last syllable. (hablar, papel)\n\nTildes mark exceptions:\n• Stress doesn't follow default → tilde required. (corazón, fácil)\n\nDistinguishing tildes:\n• tú (you) vs tu (your)\n• él (he) vs el (the)\n• sí (yes) vs si (if)\n• té (tea) vs te (you, pronoun)\n• más (more) vs mas (but)\n• qué/quién/cuándo/dónde (questions) vs que/quien/cuando/donde (relative)" }
  ],
  vocabulary: [
    { title: "Family — La Familia", items: [["mamá / madre","mom"],["papá / padre","dad"],["hermano/a","brother/sister"],["hijo/a","son/daughter"],["abuelo/a","grandfather/mother"],["tío/a","uncle/aunt"],["primo/a","cousin"],["esposo/a","husband/wife"],["novio/a","boyfriend/girlfriend"],["sobrino/a","nephew/niece"]] },
    { title: "Food — La Comida", items: [["arepa","Venezuelan corn cake"],["pan","bread"],["agua","water"],["café","coffee"],["pollo","chicken"],["carne","meat"],["pescado","fish"],["arroz","rice"],["caraotas","beans (Venezuelan)"],["frijoles","beans (general)"],["huevo","egg"],["queso","cheese"],["leche","milk"]] },
    { title: "Body — El Cuerpo", items: [["cabeza","head"],["ojo","eye"],["boca","mouth"],["nariz","nose"],["mano","hand"],["pie","foot"],["pelo","hair"],["cara","face"],["brazo","arm"],["pierna","leg"],["corazón","heart"]] },
    { title: "Time — El Tiempo", items: [["hoy","today"],["ayer","yesterday"],["mañana","tomorrow / morning"],["anoche","last night"],["ahora","now"],["después","after"],["antes","before"],["semana","week"],["mes","month"],["año","year"],["fin de semana","weekend"]] },
    { title: "Common Verbs", items: [["ser","to be (identity)"],["estar","to be (state)"],["tener","to have"],["hacer","to do/make"],["ir","to go"],["venir","to come"],["querer","to want"],["poder","to be able"],["decir","to say"],["ver","to see"],["saber","know facts"],["conocer","know people/places"]] }
  ]
};

// ═══════════════════════════════════════════════════════════════
// LESSONS — A1 (12 lessons)
// Future levels (A2, B1, B2, C1, C2) appended after the A1 array.
// ═══════════════════════════════════════════════════════════════

window.CURRICULUM.LESSONS = [

  // ─── A1 · L1 ─── Pronunciación y Acentos ─────────────────────
  { id:"L1", level:"A1", num:1,
    title:"Pronunciación y Acentos",
    subtitle:"Pronunciation, Vowels, and Accent Marks",
    study:"Spanish has 5 pure vowel sounds: a (ah), e (eh), i (ee), o (oh), u (oo). Each is short, crisp, never gliding. Accent marks (tildes) are not decorative — they tell you where to put stress. Default rules: words ending in vowel/n/s stress the second-to-last syllable (casa, hablan, comes). Words ending in other consonants stress the last syllable (papel, hablar). Any deviation = tilde required (café, fácil, papá). Tildes also distinguish meaning: sí/si, tú/tu, él/el, qué/que.",
    tables:[
      { title:"The 5 Vowel Sounds", rows:[["a","ah","casa"],["e","eh","mesa"],["i","ee","vino"],["o","oh","como"],["u","oo","luna"]] },
      { title:"Accent Distinguishes Meaning", rows:[["tú / tu","you / your"],["él / el","he / the"],["sí / si","yes / if"],["más / mas","more / but"],["qué / que","what / that"]] }
    ],
    drills:[
      { id:"L1-D1", type:"listen", q:"Listen and type the word.", audio:"casa", a:"casa",
        exp:"\"Casa\" = house. Stress on first syllable: CA-sa. No accent (ends in vowel, default stress).",
        ctx:"Default stress pattern: vowel ending → stress on second-to-last syllable. No tilde because it follows the rule.",
        ex:[{es:"Mi casa es grande.",en:"My house is big."},{es:"La casa de mi abuela.",en:"My grandmother's house."}],
        vz:"\"Mi casa es tu casa\" — universal hospitality phrase, especially common in Venezuelan culture." },
      { id:"L1-D2", type:"listen", q:"Listen and type the word.", audio:"café", a:"café",
        exp:"\"Café\" = coffee. Stress on last syllable: ca-FÉ. Tilde required.",
        ctx:"Without the accent, default stress would land on \"ca.\" Tilde overrides default and forces stress to \"fé.\"",
        ex:[{es:"Quiero un café.",en:"I want a coffee."},{es:"El café está caliente.",en:"The coffee is hot."}],
        vz:"In Venezuela: \"un cafecito\" — diminutive form, very common, suggests a casual coffee." },
      { id:"L1-D3", type:"trans_es", q:"yes (with accent)", a:"sí",
        exp:"Sí (yes) requires the accent. Without it, \"si\" means \"if.\"",
        ctx:"One of the few words where the tilde is the ONLY thing distinguishing meaning. \"Sí, voy\" (yes, I go) vs \"si voy\" (if I go).",
        ex:[{es:"Sí, te quiero.",en:"Yes, I love you."},{es:"Si llueve, no salgo.",en:"If it rains, I don't go out."}],
        vz:"\"Sí va\" or \"sí vale\" in Venezuelan = casual confirmation." },
      { id:"L1-D4", type:"trans_es", q:"you (informal, with accent)", a:"tú",
        exp:"Tú (you, subject) needs the accent. \"Tu\" = your.",
        ctx:"Tú = the person addressed. Tu = something belonging to them. \"Tú eres mi amigo\" vs \"tu amigo.\"",
        ex:[{es:"Tú eres especial.",en:"You are special."},{es:"Tu casa es bonita.",en:"Your house is pretty."}],
        vz:"In Venezuela, \"tú\" is universal. Argentina uses \"vos.\" You're using the right word for LATAM." },
      { id:"L1-D5", type:"listen", q:"Listen and type the word.", audio:"corazón", a:"corazón",
        exp:"\"Corazón\" = heart. Stress on last syllable: co-ra-ZÓN. Tilde required.",
        ctx:"Word ends in -n (default would stress \"ra\"). Tilde forces stress to \"zón\" — against default.",
        ex:[{es:"Mi corazón es tuyo.",en:"My heart is yours."},{es:"De todo corazón.",en:"From all my heart."}],
        vz:"\"Mi corazón\" or just \"corazón\" — common term of endearment in Venezuela." },
      { id:"L1-D6", type:"trans_es", q:"more (with accent)", a:"más",
        exp:"Más (more) always has the accent. \"Mas\" without accent = \"but\" (archaic).",
        ctx:"\"Más\" is one of the most common words. Always with accent. Modern Spanish uses \"pero\" for \"but.\"",
        ex:[{es:"Quiero más, por favor.",en:"I want more, please."},{es:"Es más alta que yo.",en:"She's taller than me."}],
        vz:"\"Más nada\" / \"más nunca\" = nothing else / never again. Common Venezuelan/Caribbean phrasing." },
      { id:"L1-D7", type:"listen", q:"Listen and type the word.", audio:"México", a:"México",
        alts:["Mexico"],
        exp:"\"México\" — accent on first syllable: MÉ-xi-co. Without it, default stress would be on \"xi.\"",
        ctx:"Three syllables, stress on first. Against default → tilde required on é.",
        ex:[{es:"Soy de México.",en:"I'm from Mexico."},{es:"Vamos a México.",en:"We're going to Mexico."}],
        vz:"Many Venezuelans live in Mexico due to migration — your girlfriend may know Venezuelans there." },
      { id:"L1-D8", type:"vz_recall", q:"How many vowel sounds does Spanish have?", a:"5",
        alts:["cinco","Cinco"],
        exp:"Spanish has exactly 5 vowel sounds: a, e, i, o, u. Each is one pure sound.",
        ctx:"English has ~14 vowel sounds; Spanish has 5. This is why Spanish sounds \"crisp\" — vowels never glide. Master these and your accent improves immediately.",
        ex:[{es:"a, e, i, o, u — cinco vocales.",en:"a, e, i, o, u — five vowels."},{es:"La \"e\" suena como \"eh.\"",en:"\"E\" sounds like \"eh.\""}],
        vz:"In Venezuelan/Caribbean, final 's' often softens or disappears. But the 5 vowels stay pure across all dialects." }
    ]
  },

  // ─── A1 · L2 ─── Saludos y Cortesía ──────────────────────────
  { id:"L2", level:"A1", num:2,
    title:"Saludos y Cortesía",
    subtitle:"Greetings, Goodbyes, and Polite Phrases",
    study:"Greetings vary by time: \"Buenos días\" (until noon), \"Buenas tardes\" (afternoon), \"Buenas noches\" (evening/night, also \"goodnight\"). \"Hola\" works any time. \"Por favor\" and \"gracias\" are non-negotiable in Spanish-speaking culture. Goodbyes: \"adiós\" (final), \"hasta luego\" (see you later), \"chao\" (casual, universal LATAM). Note: \"buenos días\" is plural even though singular morning. Always plural form.",
    tables:[
      { title:"Greetings by Time", rows:[["Buenos días","Good morning (until noon)"],["Buenas tardes","Good afternoon"],["Buenas noches","Good evening / goodnight"],["Hola","Hi (any time)"]] },
      { title:"Polite Essentials", rows:[["Por favor","Please"],["Gracias","Thank you"],["De nada","You're welcome"],["Perdón / Disculpe","Sorry / Excuse me"],["Con permiso","Excuse me (passing)"]] }
    ],
    drills:[
      { id:"L2-D1", type:"trans_es", q:"Good morning", a:"Buenos días",
        alts:["buenos días","¡Buenos días!"],
        exp:"\"Buenos días\" — used until noon. Note: días is plural even for singular morning.",
        ctx:"Plural form is fixed: buenos días, buenas tardes, buenas noches. Always plural. Don't use \"buen día\" (rare).",
        ex:[{es:"Buenos días, ¿cómo está usted?",en:"Good morning, how are you (formal)?"},{es:"Buenos días, mi amor.",en:"Good morning, my love."}],
        vz:"In Venezuelan homes, \"Buenos días, mi amor\" between partners is daily. Greet everyone individually when entering a home — it's polite." },
      { id:"L2-D2", type:"trans_es", q:"Thank you very much", a:"Muchas gracias",
        alts:["muchas gracias","Muchísimas gracias"],
        exp:"\"Muchas gracias\" — much/very + thanks. Standard intensifier.",
        ctx:"\"Mucho\" agrees with \"gracias\" (feminine plural) → muchas. Extreme thanks: \"muchísimas gracias.\"",
        ex:[{es:"Muchas gracias por todo.",en:"Thank you very much for everything."},{es:"Muchísimas gracias, en serio.",en:"Thank you so much, seriously."}],
        vz:"Venezuelans warm with thanks: \"Mil gracias\" (a thousand thanks) or \"Gracias, mi amor\" common." },
      { id:"L2-D3", type:"trans_es", q:"You're welcome", a:"De nada",
        alts:["de nada"],
        exp:"\"De nada\" — literally \"of nothing.\" Standard \"you're welcome.\"",
        ctx:"Other options: \"No hay de qué,\" \"Con gusto.\" \"De nada\" is the universal default.",
        ex:[{es:"— Gracias. — De nada.",en:"— Thanks. — You're welcome."},{es:"De nada, hombre.",en:"You're welcome, man."}],
        vz:"In Venezuelan: \"A la orden\" — literally \"at your service,\" used as \"you're welcome\" or when offering help." },
      { id:"L2-D4", type:"trans_es", q:"How are you? (informal)", a:"¿Cómo estás?",
        alts:["Cómo estás?","¿Cómo estás","Cómo estás"],
        exp:"\"¿Cómo estás?\" — using estar (state). Tú form: estás.",
        ctx:"Always estar (not ser) for asking how someone is. \"¿Cómo eres?\" means \"What are you like?\" (personality).",
        ex:[{es:"¿Cómo estás, amigo?",en:"How are you, friend?"},{es:"¿Cómo estás hoy?",en:"How are you today?"}],
        vz:"In Venezuelan, more common: \"¿Qué más?\" or \"¿Cómo va la cosa?\" — less stiff." },
      { id:"L2-D5", type:"trans_es", q:"Excuse me (formal, getting attention)", a:"Disculpe",
        alts:["Disculpe.","disculpe"],
        exp:"\"Disculpe\" — formal command, used to get attention politely.",
        ctx:"\"Disculpe\" (formal) for strangers/staff. \"Disculpa\" (tú) for friends. Both from disculpar (to forgive).",
        ex:[{es:"Disculpe, ¿dónde está el baño?",en:"Excuse me, where is the bathroom?"},{es:"Disculpe la molestia.",en:"Excuse the inconvenience."}],
        vz:"In Venezuela, \"disculpe\" is polite. With friends/family use \"disculpa\" or \"oye\" (hey, listen)." },
      { id:"L2-D6", type:"trans_es", q:"See you later", a:"Hasta luego",
        alts:["hasta luego","Hasta luego!"],
        exp:"\"Hasta luego\" — until later. Common goodbye, neither too formal nor casual.",
        ctx:"Variants: hasta mañana (until tomorrow), hasta pronto (see you soon). \"Adiós\" feels more final.",
        ex:[{es:"Hasta luego, gracias.",en:"See you later, thanks."},{es:"Hasta mañana, mi amor.",en:"See you tomorrow, my love."}],
        vz:"In Venezuela: \"Nos vemos\" or \"Chao\" most common. \"Hasta luego\" sounds slightly formal." },
      { id:"L2-D7", type:"listen", q:"Listen and type.", audio:"Mucho gusto en conocerte.", a:"Mucho gusto en conocerte.",
        alts:["mucho gusto en conocerte"],
        exp:"\"Great pleasure to meet you.\" Standard introduction phrase.",
        ctx:"\"Mucho gusto\" alone is also common. Adding \"en conocerte\" warmer. Response: \"El gusto es mío.\"",
        ex:[{es:"Mucho gusto, soy Ana.",en:"Nice to meet you, I'm Ana."},{es:"Mucho gusto en conocerte, Carlos.",en:"Great to meet you, Carlos."}],
        vz:"In Venezuela: \"Encantado/a\" (delighted) very common when meeting someone new — match your gender." },
      { id:"L2-D8", type:"trans_es", q:"What's your name? (informal)", a:"¿Cómo te llamas?",
        alts:["Cómo te llamas?","¿Cómo te llamas","¿Cuál es tu nombre?"],
        exp:"\"¿Cómo te llamas?\" — literally \"How do you call yourself?\" Reflexive verb llamarse.",
        ctx:"Standard. \"¿Cuál es tu nombre?\" is also valid but less colloquial. Reflexive structure is common in Spanish.",
        ex:[{es:"Hola, ¿cómo te llamas?",en:"Hi, what's your name?"},{es:"Me llamo Matthew.",en:"My name is Matthew."}],
        vz:"For \"my name is\" → \"Me llamo Matthew\" or just \"Soy Matthew.\"" },
      { id:"L2-D9", type:"trans_es", q:"Please", a:"Por favor",
        alts:["por favor"],
        exp:"\"Por favor\" — universal \"please.\"",
        ctx:"Place at start, middle, or end of request. Cultural note: omitting it sounds rude in Spanish — never skip it.",
        ex:[{es:"Por favor, ayúdame.",en:"Please, help me."},{es:"Una cerveza, por favor.",en:"A beer, please."}],
        vz:"In Venezuela, \"porfa\" — casual short form of \"por favor.\" Used in texts and casual speech." },
      { id:"L2-D10", type:"trans_es", q:"I'm sorry", a:"Lo siento",
        alts:["lo siento","Perdón","perdón","Disculpa"],
        exp:"\"Lo siento\" — I feel it. Used for apologies and condolences.",
        ctx:"\"Lo siento\" works for most apologies. \"Perdón\" is more like \"pardon me.\" \"Lo siento mucho\" for deep regret.",
        ex:[{es:"Lo siento, fue mi culpa.",en:"I'm sorry, it was my fault."},{es:"Lo siento mucho por tu pérdida.",en:"I'm so sorry for your loss."}],
        vz:"In Venezuelan: \"Disculpa, vale\" informal. \"Lo siento\" works everywhere." }
    ]
  },

  // ─── A1 · L3 ─── Pronombres y Artículos ──────────────────────
  { id:"L3", level:"A1", num:3,
    title:"Pronombres y Artículos",
    subtitle:"Pronouns, Gender, and Articles",
    study:"Spanish nouns are masculine OR feminine — no neutral. Most -O endings are masculine (el libro), most -A endings are feminine (la casa). Articles match: el/un (m), la/una (f). Plural: los/las, unos/unas. ALWAYS memorize gender with the article. Subject pronouns: yo, tú (informal), usted (formal), él/ella, nosotros, ustedes (you all — used in LATAM for both formal/informal plural), ellos/ellas. Spanish drops subject pronouns most of the time — verb endings tell who.",
    tables:[
      { title:"Subject Pronouns", rows:[["yo","I"],["tú","you (informal)"],["usted","you (formal)"],["él/ella","he/she"],["nosotros/as","we"],["ustedes","you all"],["ellos/ellas","they"]] },
      { title:"Definite Articles", rows:[["el","the (m sg)"],["la","the (f sg)"],["los","the (m pl)"],["las","the (f pl)"]] },
      { title:"Indefinite Articles", rows:[["un","a (m)"],["una","a (f)"],["unos","some (m)"],["unas","some (f)"]] }
    ],
    drills:[
      { id:"L3-D1", type:"fill", q:"___ libro está en la mesa.", hint:"the (m sg)", a:"El",
        alts:["el"],
        exp:"\"Libro\" ends in -o → masculine. The article: el.",
        ctx:"-O endings usually masculine. Common exceptions: la mano, la foto, la moto. Memorize as you encounter them.",
        ex:[{es:"El libro es interesante.",en:"The book is interesting."},{es:"El carro es nuevo.",en:"The car is new."}],
        vz:"In Venezuela: \"el carro\" is the car. Mexico might use \"el coche\" or \"el auto\" — but in Venezuela, carro dominates." },
      { id:"L3-D2", type:"fill", q:"___ casa es grande.", hint:"the (f sg)", a:"La",
        alts:["la"],
        exp:"\"Casa\" ends in -a → feminine. La casa.",
        ctx:"-A endings usually feminine. Exceptions: el día, el mapa, el problema (Greek-origin words).",
        ex:[{es:"La casa es bonita.",en:"The house is pretty."},{es:"La mesa está rota.",en:"The table is broken."}],
        vz:"\"La casa\" can colloquially mean \"home\" — \"voy pa' la casa\" (I'm going home)." },
      { id:"L3-D3", type:"trans_es", q:"a friend (m)", a:"un amigo",
        alts:["un amigo.","Un amigo"],
        exp:"\"Un\" = a (masculine indefinite). Pairs with masculine \"amigo.\"",
        ctx:"Indefinite articles match: un amigo (m), una amiga (f), unos amigos (m pl), unas amigas (f pl).",
        ex:[{es:"Tengo un amigo.",en:"I have a friend."},{es:"Es un amigo de la familia.",en:"He's a family friend."}],
        vz:"In Venezuelan: \"un pana\" replaces \"un amigo.\" Pana is gender-neutral and warmer." },
      { id:"L3-D4", type:"trans_es", q:"the books (plural)", a:"los libros",
        alts:["Los libros","los libros."],
        exp:"\"Los\" = the (m pl). Plural noun: libros (-s ending).",
        ctx:"Pluralize: add -s if vowel ending (libro→libros), -es if consonant (papel→papeles). Article also pluralizes.",
        ex:[{es:"Los libros son míos.",en:"The books are mine."},{es:"Compré los libros.",en:"I bought the books."}],
        vz:"In Caribbean/Venezuelan, final -s often softens in pronunciation, but write it normally." },
      { id:"L3-D5", type:"trans_es", q:"I am a student.", a:"Soy estudiante.",
        alts:["Yo soy estudiante.","Soy un estudiante.","Soy una estudiante."],
        exp:"\"Soy\" + estudiante. With professions/roles, no article needed.",
        ctx:"With professions, Spanish drops the article. \"Soy doctor\" not \"soy un doctor.\" Add article only if specifying.",
        ex:[{es:"Soy doctora.",en:"I'm a doctor (f)."},{es:"Es ingeniero.",en:"He's an engineer."}],
        vz:"\"Soy estudiante de español\" — useful intro. With your girlfriend's family, shows you're putting in effort." },
      { id:"L3-D6", type:"fill", q:"___ y yo somos amigos.", hint:"you (informal)", a:"Tú",
        alts:["tú"],
        exp:"\"Tú\" + yo → we. Accent on tú distinguishes from \"tu\" (your).",
        ctx:"\"Tú y yo\" common phrase. Yo always second when paired with another pronoun in subject.",
        ex:[{es:"Tú y yo nos vemos mañana.",en:"You and I see each other tomorrow."},{es:"Tú eres mi amigo.",en:"You are my friend."}],
        vz:"\"Tú y yo, chamo, somos panas\" — full Venezuelan flavor." },
      { id:"L3-D7", type:"trans_es", q:"They (women) are sisters.", a:"Ellas son hermanas.",
        alts:["Son hermanas.","Ellas son hermanas"],
        exp:"\"Ellas\" (all-female) + son + hermanas.",
        ctx:"Use \"ellas\" only for all-female group. Mixed/male: \"ellos.\" Default to ellos if unsure.",
        ex:[{es:"Ellas son mis hermanas.",en:"They are my sisters."},{es:"Ellos son mis amigos.",en:"They are my friends."}],
        vz:"In Venezuelan, often drop pronoun: \"Son hermanas\" — context tells listener." },
      { id:"L3-D8", type:"vz_recall", q:"What's the LATAM word for \"you all\" (formal AND informal)?", a:"ustedes",
        alts:["Ustedes"],
        exp:"\"Ustedes\" — used for ALL plural \"you\" in Latin America. Spain uses \"vosotros\" for informal, but LATAM does not.",
        ctx:"Key LATAM rule: ustedes covers everything plural-you. Verb ending matches: ustedes hablan, comen, viven (just like ellos).",
        ex:[{es:"Ustedes son mi familia.",en:"You all are my family."},{es:"¿Ustedes hablan inglés?",en:"Do you all speak English?"}],
        vz:"In Venezuela (and all LATAM): NEVER vosotros. Always ustedes. This is what makes you sound Latin American." },
      { id:"L3-D9", type:"fill", q:"___ y yo vamos al cine.", hint:"she", a:"Ella",
        alts:["ella"],
        exp:"\"Ella\" (she) + yo → we. Subject position.",
        ctx:"When pairing pronouns, yo always second. Combined treated as nosotros: \"vamos.\"",
        ex:[{es:"Ella y yo somos amigas.",en:"She and I are friends."},{es:"Ellos y yo trabajamos juntos.",en:"They and I work together."}],
        vz:"\"Ella y yo, ¿qué más?\" — Venezuelan casual phrasing." },
      { id:"L3-D10", type:"trans_es", q:"the women", a:"las mujeres",
        alts:["las mujeres."],
        exp:"\"Las\" + mujeres (plural of mujer).",
        ctx:"\"Mujer\" ends in consonant (-r), plural adds -es: mujeres. Article matches: las.",
        ex:[{es:"Las mujeres son fuertes.",en:"Women are strong."},{es:"Las mujeres venezolanas son hermosas.",en:"Venezuelan women are beautiful."}],
        vz:"\"Las chamas\" is casual Venezuelan for \"the girls\" or \"the women.\"" }
    ]
  },

  // ─── A1 · L4 ─── Ser vs Estar ────────────────────────────────
  { id:"L4", level:"A1", num:4,
    title:"Ser vs Estar",
    subtitle:"The Two Ways to Say \"To Be\"",
    study:"Spanish has two verbs for \"to be\": SER and ESTAR — not interchangeable. SER = identity, characteristics, origin, profession, time. \"Soy alta\" (I'm tall — that's who I am). ESTAR = location, temporary states, ongoing actions. \"Estoy cansada\" (I'm tired — temporary). Same adjective changes meaning: \"Es aburrido\" (he is boring) vs \"Está aburrido\" (he is bored). Master at A1 — never goes away.",
    tables:[
      { title:"SER (present)", rows:[["yo soy"],["tú eres"],["él/ella es"],["nosotros somos"],["ustedes/ellos son"]] },
      { title:"ESTAR (present)", rows:[["yo estoy"],["tú estás"],["él/ella está"],["nosotros estamos"],["ustedes/ellos están"]] },
      { title:"When to Use", rows:[["SER","Identity, origin, time, profession, traits"],["ESTAR","Location, feelings, ongoing actions, temporary states"]] }
    ],
    drills:[
      { id:"L4-D1", type:"fill", q:"Yo ___ de Estados Unidos.", hint:"ser, yo", a:"soy",
        exp:"Origin → ser. \"Yo soy de Estados Unidos.\"",
        ctx:"Origin = permanent identity → always SER. \"Soy de\" is the formula. Never estar for origin.",
        ex:[{es:"Soy de los Estados Unidos.",en:"I'm from the US."},{es:"Ella es de Venezuela.",en:"She's from Venezuela."}],
        vz:"\"Ella es de Caracas\" — Venezuelan capital. \"Es caraqueña\" if specifying. From Maracaibo: \"maracucho.\"" },
      { id:"L4-D2", type:"fill", q:"María ___ cansada hoy.", hint:"estar, ella", a:"está",
        exp:"Temporary state → estar.",
        ctx:"Tiredness is temporary, not a permanent trait. Always estar for feelings: cansada, feliz, enferma.",
        ex:[{es:"Estoy cansada hoy.",en:"I'm tired today."},{es:"Está enferma desde ayer.",en:"She's been sick since yesterday."}],
        vz:"Casual Venezuelan: \"Está fundida\" (= burnt out) or \"Está muerta\" (dead-tired)." },
      { id:"L4-D3", type:"trans_es", q:"I am American.", a:"Soy estadounidense.",
        alts:["Yo soy estadounidense.","Soy americano.","Soy americana."],
        exp:"Nationality → ser. \"Estadounidense\" same form for m/f.",
        ctx:"\"Americano\" technically means \"from the Americas\" (includes LATAM). \"Estadounidense\" more precise.",
        ex:[{es:"Soy estadounidense.",en:"I'm American (from the US)."},{es:"Mi novia es venezolana.",en:"My girlfriend is Venezuelan."}],
        vz:"\"Soy estadounidense, mi novia es venezolana\" — gets warm reactions from Venezuelans abroad." },
      { id:"L4-D4", type:"trans_es", q:"The book is on the table.", a:"El libro está en la mesa.",
        alts:["El libro está sobre la mesa."],
        exp:"Location → estar.",
        ctx:"Location of objects, people, places → ALWAYS estar. Don't say \"el libro es en la mesa.\"",
        ex:[{es:"El carro está en la calle.",en:"The car is in the street."},{es:"Estoy en casa.",en:"I'm at home."}],
        vz:"\"Está en la casa, vale\" — vale ending makes it casual Venezuelan." },
      { id:"L4-D5", type:"trans_es", q:"She is a doctor.", a:"Ella es doctora.",
        alts:["Es doctora."],
        exp:"Profession → ser. No article needed.",
        ctx:"Profession with ser: no \"a/an.\" Add article only if specifying: \"Soy un doctor experimentado.\"",
        ex:[{es:"Soy maestra.",en:"I'm a teacher (f)."},{es:"Mi mamá es enfermera.",en:"My mom is a nurse."}],
        vz:"In Venezuela, doctora/doctor is respectful address for medical professionals — and even university grads." },
      { id:"L4-D6", type:"trans_es", q:"It's two o'clock.", a:"Son las dos.",
        exp:"Time → ser. \"Son las\" plural for hours after 1.",
        ctx:"Time uses ser. \"Es la una\" (1:00 only). \"Son las dos/tres...\" Always feminine articles (la/las).",
        ex:[{es:"Son las tres de la tarde.",en:"It's 3 PM."},{es:"Es la una en punto.",en:"It's exactly 1:00."}],
        vz:"\"¿Qué hora es?\" → \"Son las dos en punto.\" Universal." },
      { id:"L4-D7", type:"trans_es", q:"I am happy today.", a:"Estoy feliz hoy.",
        alts:["Yo estoy feliz hoy.","Estoy contento hoy.","Estoy contenta hoy."],
        exp:"Feeling → estar.",
        ctx:"Emotions/moods are temporary states → estar. \"Soy feliz\" (I'm a happy person) is rare.",
        ex:[{es:"Estoy feliz contigo.",en:"I'm happy with you."},{es:"Hoy estoy contenta.",en:"Today I'm happy."}],
        vz:"In Venezuelan: \"Estoy fino\" or \"Estoy chévere\" = I'm great. Use these instead of \"estoy bien.\"" },
      { id:"L4-D8", type:"listen", q:"Listen and type.", audio:"Mi novia es venezolana y está en Caracas.", a:"Mi novia es venezolana y está en Caracas.",
        alts:["mi novia es venezolana y está en caracas"],
        exp:"\"My girlfriend is Venezuelan (ser) and is in Caracas (estar).\" Both verbs, perfect contrast.",
        ctx:"Nationality = ser, location = estar. Constant pattern.",
        ex:[{es:"Soy alto y estoy en casa.",en:"I'm tall (ser) and I'm at home (estar)."},{es:"Es médica y está en el hospital.",en:"She's a doctor and at the hospital."}],
        vz:"\"Mi novia es venezolana\" — your daily phrase. Make it second nature." },
      { id:"L4-D9", type:"trans_es", q:"He is bored.", a:"Está aburrido.",
        alts:["Él está aburrido."],
        exp:"Temporary state (bored) → estar. Compare: \"Es aburrido\" = he's a boring person.",
        ctx:"Same word, different verb, different meaning. Verb chooses the meaning: ser = identity, estar = state.",
        ex:[{es:"Está aburrido en el trabajo.",en:"He's bored at work."},{es:"Es aburrido — nunca habla.",en:"He's boring — he never talks."}],
        vz:"\"¡Qué ladilla!\" Venezuelan = What a drag! / How boring!" },
      { id:"L4-D10", type:"fill", q:"Mi familia ___ en Texas, pero yo ___ de Florida.", hint:"location, then origin", a:"está, soy",
        alts:["está soy","esta, soy","esta soy"],
        exp:"Location (en Texas) = estar. Origin (de Florida) = ser. Comma-separated.",
        ctx:"Both verbs in context. Family currently located → estar. You originated → ser.",
        ex:[{es:"Estoy en México pero soy de EE.UU.",en:"I'm in Mexico but I'm from the US."},{es:"Está en casa, es médica.",en:"She's at home, she's a doctor."}],
        vz:"\"Mi novia está en Caracas pero es de Maracay\" — common pattern." }
    ]
  },

  // ─── A1 · L5 ─── Presente -AR ────────────────────────────────
  { id:"L5", level:"A1", num:5,
    title:"Presente -AR",
    subtitle:"Present Tense Regular -AR Verbs",
    study:"-AR verbs are the largest group. Drop -ar, add: yo -o, tú -as, él/ella -a, nosotros -amos, ustedes/ellos -an. NO accents in present tense. Hablar = to speak: hablo, hablas, habla, hablamos, hablan. Common -AR verbs: cantar, bailar, trabajar, estudiar, comprar, escuchar, mirar, caminar, llevar, amar.",
    tables:[
      { title:"hablar — to speak", rows:[["yo","hablo"],["tú","hablas"],["él/ella","habla"],["nosotros","hablamos"],["ustedes/ellos","hablan"]] },
      { title:"Common -AR Verbs", rows:[["cantar","sing"],["bailar","dance"],["trabajar","work"],["estudiar","study"],["comprar","buy"],["escuchar","listen"],["caminar","walk"],["amar","love"]] }
    ],
    drills:[
      { id:"L5-D1", type:"conj", q:"hablar — yo", a:"hablo",
        exp:"-AR yo: drop -ar, add -o. No accent.",
        ctx:"Yo form is foundational. Same -o ending across all verb types in present tense.",
        ex:[{es:"Hablo español poco.",en:"I speak Spanish a little."},{es:"Hablo con mi novia todos los días.",en:"I speak with my girlfriend every day."}],
        vz:"\"Hablo poquito español\" — humility goes far in Venezuela. Diminutive \"poquito\" common." },
      { id:"L5-D2", type:"conj", q:"trabajar — tú", a:"trabajas",
        exp:"-AR tú: drop -ar, add -as.",
        ctx:"Tú endings always have -s in present (across all verb types). Hablas, comes, vives — consistent.",
        ex:[{es:"¿Tú trabajas hoy?",en:"Do you work today?"},{es:"Trabajas mucho, mi amor.",en:"You work a lot, my love."}],
        vz:"\"¿Tú trabajas?\" — common opener. Be ready to share." },
      { id:"L5-D3", type:"conj", q:"cantar — ella", a:"canta",
        exp:"-AR él/ella: drop -ar, add -a.",
        ctx:"Same form for usted (formal you): \"Usted canta.\"",
        ex:[{es:"Ella canta muy bien.",en:"She sings very well."},{es:"Mi mamá canta en la iglesia.",en:"My mom sings at church."}],
        vz:"\"Canta burda de bien\" — Venezuelan intensifier." },
      { id:"L5-D4", type:"conj", q:"estudiar — nosotros", a:"estudiamos",
        exp:"-AR nosotros: drop -ar, add -amos. Same as preterite — context decides.",
        ctx:"-AR nosotros identical in present and preterite. Time markers (ahora, ayer) disambiguate.",
        ex:[{es:"Estudiamos español juntos.",en:"We study Spanish together."},{es:"Trabajamos mucho hoy.",en:"We work a lot today."}],
        vz:"\"Estudiamos español juntos\" — invitation line for a Venezuelan friend." },
      { id:"L5-D5", type:"conj", q:"bailar — ellos", a:"bailan",
        exp:"-AR ustedes/ellos: drop -ar, add -an.",
        ctx:"Ustedes and ellos identical across all tenses in LATAM.",
        ex:[{es:"Ellos bailan salsa.",en:"They dance salsa."},{es:"Ustedes bailan muy bien.",en:"You all dance very well."}],
        vz:"In Venezuela: salsa, merengue, reggaeton huge. \"Bailan salsa\" sets a Caribbean scene." },
      { id:"L5-D6", type:"trans_es", q:"I work in an office.", a:"Trabajo en una oficina.",
        alts:["Yo trabajo en una oficina."],
        exp:"Trabajo + en + una oficina (feminine).",
        ctx:"\"En\" for \"in/at\" location. \"Una\" because oficina is feminine.",
        ex:[{es:"Trabajo en casa.",en:"I work at home."},{es:"Trabajo desde casa.",en:"I work from home."}],
        vz:"\"Trabajo en una oficina, pero ahora desde casa\" — universal post-pandemic phrase." },
      { id:"L5-D7", type:"trans_es", q:"She buys coffee every morning.", a:"Compra café todas las mañanas.",
        alts:["Ella compra café todas las mañanas.","Compra café cada mañana.","Ella compra café cada mañana."],
        exp:"\"Todas las mañanas\" = every morning (lit. all the mornings).",
        ctx:"Plural form: \"todas las mañanas.\" Alternative: \"cada mañana\" (each morning).",
        ex:[{es:"Compro pan los lunes.",en:"I buy bread on Mondays."},{es:"Compras todo en el supermercado.",en:"You buy everything at the supermarket."}],
        vz:"Venezuelan mornings revolve around coffee. \"Un guayoyo\" (weak black) or \"un marrón\" (medium)." },
      { id:"L5-D8", type:"listen", q:"Listen and type.", audio:"Caminamos por el parque todos los días.", a:"Caminamos por el parque todos los días.",
        alts:["caminamos por el parque todos los días"],
        exp:"\"We walk through the park every day.\"",
        ctx:"\"Por\" for movement through/around. \"Caminar por el parque\" = around the park, vs \"caminar al parque\" = to the park.",
        ex:[{es:"Caminamos por la ciudad.",en:"We walk through the city."},{es:"Camino al trabajo.",en:"I walk to work."}],
        vz:"\"Caminamos burda\" = we walk a ton. Adds intensity." },
      { id:"L5-D9", type:"trans_es", q:"They listen to music.", a:"Escuchan música.",
        alts:["Ellos escuchan música.","Ellas escuchan música.","Escuchan la música."],
        exp:"Escuchar already includes \"to listen TO\" — no preposition.",
        ctx:"Don't add \"a\" — wrong. Same with \"buscar\" (to look FOR): \"buscan trabajo\" not \"buscan por trabajo.\"",
        ex:[{es:"Escucho música todos los días.",en:"I listen to music every day."},{es:"¿Qué música escuchas?",en:"What music do you listen to?"}],
        vz:"Venezuelan music: salsa, merengue, gaita, reggaeton. \"¿Qué música escuchas?\" — instant connection." },
      { id:"L5-D10", type:"trans_es", q:"I love you.", a:"Te amo.",
        alts:["Te quiero.","Te amo mucho."],
        exp:"\"Te amo\" — strong romantic. \"Te quiero\" — also love, less intense.",
        ctx:"Amar is romantic/deep love. Querer can mean \"want\" or \"love\" by context. \"Te quiero\" widely between partners early. \"Te amo\" reserved for serious commitment.",
        ex:[{es:"Te amo, mi vida.",en:"I love you, my life."},{es:"Te quiero mucho.",en:"I love you a lot."}],
        vz:"In Venezuelan: \"Te amo burda\" or \"te amo full\" = I love you a ton." }
    ]
  },

  // ─── A1 · L6 ─── Presente -ER y -IR ──────────────────────────
  { id:"L6", level:"A1", num:6,
    title:"Presente -ER y -IR",
    subtitle:"Present Tense Regular -ER and -IR",
    study:"-ER and -IR share most endings — only nosotros differs. -ER endings: -o, -es, -e, -emos, -en. -IR endings: -o, -es, -e, -imos, -en. Only -emos vs -imos differs. Common -ER: comer (eat), beber (drink), leer (read), aprender (learn), correr (run). Common -IR: vivir (live), escribir (write), abrir (open), recibir (receive), subir (climb).",
    tables:[
      { title:"comer (-ER)", rows:[["yo","como"],["tú","comes"],["él/ella","come"],["nosotros","comemos"],["ustedes/ellos","comen"]] },
      { title:"vivir (-IR)", rows:[["yo","vivo"],["tú","vives"],["él/ella","vive"],["nosotros","vivimos"],["ustedes/ellos","viven"]] },
      { title:"Common -ER/-IR", rows:[["beber","drink"],["leer","read"],["aprender","learn"],["correr","run"],["escribir","write"],["abrir","open"],["recibir","receive"],["subir","climb"]] }
    ],
    drills:[
      { id:"L6-D1", type:"conj", q:"comer — yo", a:"como",
        exp:"-ER yo: drop -er, add -o.",
        ctx:"Same yo ending as -AR (-o). All present yo forms end in -o (rare exceptions: soy, voy, doy).",
        ex:[{es:"Como arepas para el desayuno.",en:"I eat arepas for breakfast."},{es:"Como muy poco.",en:"I eat very little."}],
        vz:"\"Como arepas\" — declares Venezuelan integration. Family will know you're trying." },
      { id:"L6-D2", type:"conj", q:"vivir — tú", a:"vives",
        exp:"-IR tú: drop -ir, add -es. Same as -ER tú.",
        ctx:"Tú endings identical for -ER and -IR: -es. Comes, vives, bebes, abres.",
        ex:[{es:"¿Dónde vives?",en:"Where do you live?"},{es:"Vives muy lejos.",en:"You live very far away."}],
        vz:"\"¿Dónde vives?\" — common question. Answer with city: \"Vivo en Dallas.\"" },
      { id:"L6-D3", type:"conj", q:"escribir — ella", a:"escribe",
        exp:"-IR él/ella: drop -ir, add -e.",
        ctx:"Él/ella endings identical for -ER and -IR: -e.",
        ex:[{es:"Escribe poemas.",en:"She writes poems."},{es:"Escribe en español.",en:"He writes in Spanish."}],
        vz:"\"Escribe burda\" or \"escribe full\" — Venezuelan intensifiers." },
      { id:"L6-D4", type:"conj", q:"comer — nosotros", a:"comemos",
        exp:"-ER nosotros: -emos.",
        ctx:"Critical: -ER nosotros = -emos. -IR nosotros = -imos. ONLY place they diverge.",
        ex:[{es:"Comemos juntos.",en:"We eat together."},{es:"Comemos arepas los domingos.",en:"We eat arepas on Sundays."}],
        vz:"Sunday family meals = Venezuelan tradition. \"Comemos en familia los domingos.\"" },
      { id:"L6-D5", type:"conj", q:"vivir — nosotros", a:"vivimos",
        exp:"-IR nosotros: -imos. Same form as preterite.",
        ctx:"\"Vivimos en Caracas\" — present or past depending on context. Time markers clarify.",
        ex:[{es:"Vivimos en Estados Unidos ahora.",en:"We live in the US now."},{es:"Vivimos felices.",en:"We live happily."}],
        vz:"\"Vivimos en USA pero somos venezolanos\" — diaspora identity statement." },
      { id:"L6-D6", type:"conj", q:"leer — ellos", a:"leen",
        exp:"-ER ustedes/ellos: -en.",
        ctx:"Ellos endings same for -ER and -IR: -en.",
        ex:[{es:"Leen muchos libros.",en:"They read many books."},{es:"Mis hijos leen todos los días.",en:"My kids read every day."}],
        vz:"\"Leen burda\" or simply \"leen mucho.\"" },
      { id:"L6-D7", type:"trans_es", q:"We learn Spanish.", a:"Aprendemos español.",
        alts:["Nosotros aprendemos español.","Aprendemos el español."],
        exp:"Aprendemos (nos., aprender) + español.",
        ctx:"Aprender is a stable -ER verb. \"Aprendemos juntos\" if learning together.",
        ex:[{es:"Aprendo cada día.",en:"I learn every day."},{es:"Aprendemos rápido.",en:"We learn fast."}],
        vz:"\"Aprendo español por mi novia venezolana\" — perfect motivation. Honest, warm." },
      { id:"L6-D8", type:"listen", q:"Listen and type.", audio:"Escribo cartas a mi familia.", a:"Escribo cartas a mi familia.",
        alts:["escribo cartas a mi familia"],
        exp:"\"I write letters to my family.\"",
        ctx:"\"A mi familia\" — personal a, required when action directed at people.",
        ex:[{es:"Escribo a mi novia.",en:"I write to my girlfriend."},{es:"Escribo correos electrónicos.",en:"I write emails."}],
        vz:"Modern Venezuelan: \"Le escribo por WhatsApp\" universal." },
      { id:"L6-D9", type:"trans_es", q:"He drinks water.", a:"Bebe agua.",
        alts:["Él bebe agua.","Toma agua.","Él toma agua."],
        exp:"Bebe (beber) OR toma (tomar). Both valid.",
        ctx:"\"Beber\" is textbook. \"Tomar\" more common in spoken LATAM (and means \"take\" too). Tomar more natural.",
        ex:[{es:"Toma agua todos los días.",en:"He drinks water every day."},{es:"¿Qué tomas?",en:"What are you drinking?"}],
        vz:"In Venezuela: tomar way more common than beber. \"Toma agua\" natural; \"bebe agua\" textbook." },
      { id:"L6-D10", type:"trans_es", q:"They open the doors.", a:"Abren las puertas.",
        alts:["Ellos abren las puertas.","Ellas abren las puertas."],
        exp:"Abren (abrir) + las puertas.",
        ctx:"\"Las puertas\" — feminine plural article + noun. Puerta ends in -a, -s for plural.",
        ex:[{es:"Abren las puertas a las nueve.",en:"They open the doors at nine."},{es:"Abro la puerta.",en:"I open the door."}],
        vz:"\"¿A qué hora abren?\" — useful question for shops in Venezuela." },
      { id:"L6-D11", type:"trans_es", q:"I receive many messages.", a:"Recibo muchos mensajes.",
        alts:["Yo recibo muchos mensajes."],
        exp:"Recibo + muchos mensajes (m pl agreement).",
        ctx:"\"Mucho\" changes: muchos (m pl), muchas (f pl), mucho/mucha (sg). Always match noun.",
        ex:[{es:"Recibo correos todos los días.",en:"I receive emails every day."},{es:"Recibimos muchas llamadas.",en:"We receive a lot of calls."}],
        vz:"\"Recibo full mensajes\" — Venezuelan \"full\" = a lot." },
      { id:"L6-D12", type:"trans_es", q:"We run in the park.", a:"Corremos en el parque.",
        alts:["Nosotros corremos en el parque.","Corremos por el parque."],
        exp:"Corremos + en/por el parque.",
        ctx:"\"En\" for location, \"por\" for movement through. Both work.",
        ex:[{es:"Corro todas las mañanas.",en:"I run every morning."},{es:"Corre rápido.",en:"He runs fast."}],
        vz:"\"Corremos burda, chamo\" — full Venezuelan flavor." }
    ]
  },

  // ─── A1 · L7 ─── Verbos Irregulares Comunes ──────────────────
  { id:"L7", level:"A1", num:7,
    title:"Verbos Irregulares Comunes",
    subtitle:"Common Irregular Verbs — tener, ir, hacer, querer, poder",
    study:"Five essential irregular verbs in present tense. TENER (have): tengo, tienes, tiene, tenemos, tienen — yo gets a g. IR (go): voy, vas, va, vamos, van — completely irregular. HACER (do/make): hago, haces, hace, hacemos, hacen — yo gets g. QUERER (want): quiero, quieres, quiere, queremos, quieren — stem e→ie. PODER (be able): puedo, puedes, puede, podemos, pueden — stem o→ue. Memorize all five.",
    tables:[
      { title:"tener (have)", rows:[["yo tengo"],["tú tienes"],["él/ella tiene"],["nosotros tenemos"],["ustedes/ellos tienen"]] },
      { title:"ir (go)", rows:[["yo voy"],["tú vas"],["él/ella va"],["nosotros vamos"],["ustedes/ellos van"]] },
      { title:"hacer (do/make)", rows:[["yo hago"],["tú haces"],["él/ella hace"],["nosotros hacemos"],["ustedes/ellos hacen"]] },
      { title:"querer (want)", rows:[["yo quiero"],["tú quieres"],["él/ella quiere"],["nosotros queremos"],["ustedes/ellos quieren"]] },
      { title:"poder (be able)", rows:[["yo puedo"],["tú puedes"],["él/ella puede"],["nosotros podemos"],["ustedes/ellos pueden"]] }
    ],
    drills:[
      { id:"L7-D1", type:"conj", q:"tener — yo", a:"tengo",
        exp:"Tener yo: tengo. The g irregular only in yo form.",
        ctx:"Several common verbs add g to yo: tengo, hago, pongo, salgo, vengo, digo. Memorize this group.",
        ex:[{es:"Tengo veinte años.",en:"I'm 20 years old (lit. I have 20 years)."},{es:"Tengo hambre.",en:"I'm hungry (lit. I have hunger)."}],
        vz:"\"Tengo hambre/sed/sueño\" — Spanish uses tener for many states English uses \"to be.\" Critical pattern." },
      { id:"L7-D2", type:"conj", q:"ir — yo", a:"voy",
        exp:"Ir yo: voy. Doesn't even resemble infinitive.",
        ctx:"Most irregular verb in Spanish. Memorize: voy, vas, va, vamos, van.",
        ex:[{es:"Voy a la casa.",en:"I'm going home."},{es:"Voy a comer.",en:"I'm going to eat."}],
        vz:"\"Voy pa' la casa\" / \"Voy pa' allá\" — pa' = para, super common Venezuelan contraction." },
      { id:"L7-D3", type:"conj", q:"hacer — yo", a:"hago",
        exp:"Hacer yo: hago. Both g insertion AND c→g change.",
        ctx:"\"Hago.\" Other forms: haces, hace, hacemos, hacen — keep original c.",
        ex:[{es:"Hago mi tarea.",en:"I do my homework."},{es:"Hago ejercicio todos los días.",en:"I exercise every day."}],
        vz:"\"¿Qué haces?\" → \"Hago [actividad]\" most common conversation pattern." },
      { id:"L7-D4", type:"conj", q:"querer — tú", a:"quieres",
        exp:"Querer tú: quieres. Stem e→ie.",
        ctx:"Stem-changing in all forms EXCEPT nosotros: quiero, quieres, quiere, queremos (no change), quieren.",
        ex:[{es:"¿Tú quieres comer?",en:"Do you want to eat?"},{es:"¿Quieres ir al cine?",en:"Do you want to go to the movies?"}],
        vz:"\"¿Quieres ir, mi amor?\" — sweet Venezuelan invitation." },
      { id:"L7-D5", type:"conj", q:"poder — nosotros", a:"podemos",
        exp:"Poder nosotros: podemos. Nosotros KEEPS original o.",
        ctx:"Like querer, poder stem-changes (o→ue) EXCEPT nosotros. Don't say \"puedemos\" — wrong.",
        ex:[{es:"Podemos hacerlo juntos.",en:"We can do it together."},{es:"No podemos ir hoy.",en:"We can't go today."}],
        vz:"\"No podemos ir hoy, vale\" — vale softens." },
      { id:"L7-D6", type:"trans_es", q:"I have a Venezuelan girlfriend.", a:"Tengo una novia venezolana.",
        alts:["Yo tengo una novia venezolana.","Tengo novia venezolana."],
        exp:"Tengo + una novia venezolana. Adjective agrees with feminine noun.",
        ctx:"Adjectives generally come after the noun and agree in gender/number.",
        ex:[{es:"Tengo una hermana mayor.",en:"I have an older sister."},{es:"Tengo un perro pequeño.",en:"I have a small dog."}],
        vz:"\"Tengo una novia venezolana\" — your daily phrase. Be ready for: \"¿De qué parte?\" — know your girlfriend's home city." },
      { id:"L7-D7", type:"trans_es", q:"What do you do? (work)", a:"¿A qué te dedicas?",
        alts:["A qué te dedicas?","¿En qué trabajas?","En qué trabajas?","¿Qué haces?","Qué haces?"],
        exp:"\"¿A qué te dedicas?\" most common professional question.",
        ctx:"\"¿Qué haces?\" can mean work OR what you're doing right now — context decides. \"¿A qué te dedicas?\" unambiguous about profession.",
        ex:[{es:"— ¿A qué te dedicas? — Soy ingeniero.",en:"— What do you do? — I'm an engineer."},{es:"¿En qué trabajas?",en:"What's your work?"}],
        vz:"\"¿Qué haces, chamo?\" — friendly version. Ambiguous." },
      { id:"L7-D8", type:"trans_es", q:"We want to go to the beach.", a:"Queremos ir a la playa.",
        alts:["Nosotros queremos ir a la playa."],
        exp:"Queremos + ir (inf) + a la playa.",
        ctx:"Querer + infinitive = want to do. Second verb stays infinitive.",
        ex:[{es:"Quiero comer arepas.",en:"I want to eat arepas."},{es:"Quieres bailar.",en:"You want to dance."}],
        vz:"\"Queremos ir a Los Roques\" — drop a real Venezuelan beach name to score points." },
      { id:"L7-D9", type:"listen", q:"Listen and type.", audio:"No puedo ir hoy, tengo trabajo.", a:"No puedo ir hoy, tengo trabajo.",
        alts:["no puedo ir hoy tengo trabajo"],
        exp:"\"I can't go today, I have work.\" Two verbs: poder + tener.",
        ctx:"\"No puedo ir\" + \"Tengo trabajo\" — used to politely decline plans.",
        ex:[{es:"No puedo, tengo otra cosa.",en:"I can't, I have something else."},{es:"Hoy no puedo, mañana sí.",en:"Today I can't, tomorrow yes."}],
        vz:"\"No puedo, vale\" — softening Venezuelan ending." },
      { id:"L7-D10", type:"trans_es", q:"He goes to work every day.", a:"Va al trabajo todos los días.",
        alts:["Él va al trabajo todos los días.","Va a trabajar todos los días."],
        exp:"Va + al trabajo + todos los días. \"Al\" = a + el (always contracts).",
        ctx:"\"A + el\" → \"al\" always. Never \"a el.\" But \"a la,\" \"a los,\" \"a las\" don't contract.",
        ex:[{es:"Va al gimnasio.",en:"He goes to the gym."},{es:"Voy al cine esta noche.",en:"I'm going to the movies tonight."}],
        vz:"Caracas commute jokes: \"Va al trabajo, pero el tráfico está arrecho.\"" },
      { id:"L7-D11", type:"conj", q:"hacer — ellos", a:"hacen",
        exp:"Hacer ellos: hacen. Regular -er ending. Only yo (hago) is irregular.",
        ctx:"Most -er irregulars only weird in yo form. Tienes/tiene/tenemos/tienen all regular pattern.",
        ex:[{es:"¿Qué hacen ustedes?",en:"What do you all do?"},{es:"Hacen tareas juntos.",en:"They do tasks together."}],
        vz:"\"¿Qué hacen, chamos?\" — to a group of friends." },
      { id:"L7-D12", type:"trans_es", q:"They have a big house.", a:"Tienen una casa grande.",
        alts:["Ellos tienen una casa grande.","Ellas tienen una casa grande."],
        exp:"Tienen + una casa grande.",
        ctx:"\"Grande\" doesn't change for gender (just number: grandes for plural).",
        ex:[{es:"Tienen una casa grande.",en:"They have a big house."},{es:"Tenemos un perro grande.",en:"We have a big dog."}],
        vz:"\"Tienen una casa burda de grande\" — Venezuelan intensifier." }
    ]
  },

  // ─── A1 · L8 ─── Números, Tiempo y Fechas ────────────────────
  { id:"L8", level:"A1", num:8,
    title:"Números, Tiempo y Fechas",
    subtitle:"Numbers, Time, and Dates",
    study:"Numbers 0-15 each unique: cero, uno, dos, tres, cuatro, cinco, seis, siete, ocho, nueve, diez, once, doce, trece, catorce, quince. 16-19 use \"diecis-\": dieciséis, diecisiete... 20s use \"veinti-\": veintiuno, veintidós... 30+ uses \"y\": treinta y uno. Time: \"Es la una\" (1:00), \"Son las dos/tres/etc.\" Days (lowercase): lunes, martes, miércoles, jueves, viernes, sábado, domingo. Months also lowercase.",
    tables:[
      { title:"Numbers 1-20", rows:[["1-5","uno, dos, tres, cuatro, cinco"],["6-10","seis, siete, ocho, nueve, diez"],["11-15","once, doce, trece, catorce, quince"],["16-20","dieciséis, diecisiete, dieciocho, diecinueve, veinte"]] },
      { title:"Tens", rows:[["20","veinte"],["30","treinta"],["40","cuarenta"],["50","cincuenta"],["60","sesenta"],["70","setenta"],["80","ochenta"],["90","noventa"],["100","cien"]] },
      { title:"Days & Months", rows:[["Days","lunes, martes, miércoles, jueves, viernes, sábado, domingo"],["Months","enero, febrero, marzo, abril, mayo, junio, julio, agosto, septiembre, octubre, noviembre, diciembre"]] }
    ],
    drills:[
      { id:"L8-D1", type:"trans_es", q:"twenty-five", a:"veinticinco",
        alts:["Veinticinco","veinte y cinco"],
        exp:"\"Veinticinco\" — 21-29 written as one word.",
        ctx:"21-29 unique: single word with veinti-. From 31, switch back to multiple words with \"y\": treinta y uno.",
        ex:[{es:"Tengo veinticinco años.",en:"I'm 25 years old."},{es:"Veinticinco después de las dos.",en:"25 past 2."}],
        vz:"\"Tengo veinticinco años y mi novia es venezolana\" — common context." },
      { id:"L8-D2", type:"trans_es", q:"It's 3:00 PM.", a:"Son las tres de la tarde.",
        alts:["Son las 3 de la tarde.","Son las tres p.m."],
        exp:"\"Son las tres + de la tarde.\" 12pm-7pm = de la tarde.",
        ctx:"Spanish doesn't use AM/PM commonly. \"De la mañana\" (AM), \"de la tarde\" (12-7pm), \"de la noche\" (7pm+).",
        ex:[{es:"Son las nueve de la mañana.",en:"It's 9 AM."},{es:"Son las ocho de la noche.",en:"It's 8 PM."}],
        vz:"Casually: \"Son como las tres\" — como = approximately." },
      { id:"L8-D3", type:"trans_es", q:"What day is it today?", a:"¿Qué día es hoy?",
        alts:["Qué día es hoy?"],
        exp:"\"¿Qué día es hoy?\" — answer: \"Hoy es lunes/martes...\"",
        ctx:"Days of week masculine, lowercase. \"Es lunes,\" not \"Es Lunes.\"",
        ex:[{es:"Hoy es martes.",en:"Today is Tuesday."},{es:"¿Qué día es mañana? — Es miércoles.",en:"What day is tomorrow? — It's Wednesday."}],
        vz:"\"Sábado\" for parties, \"Domingo\" for family. \"¿Qué hacemos el sábado?\" — common weekend planning." },
      { id:"L8-D4", type:"trans_es", q:"It's 1:00.", a:"Es la una.",
        exp:"Singular: \"Es la una.\" Only 1:00 is singular.",
        ctx:"From 2: \"Son las dos/tres...\" Always feminine (la, las).",
        ex:[{es:"Es la una en punto.",en:"It's exactly 1:00."},{es:"Es la una y media.",en:"It's 1:30."}],
        vz:"Lunch in Venezuela tends later (1-2pm). \"Es la una de la tarde\" — typical lunch time." },
      { id:"L8-D5", type:"listen", q:"Listen and type the number.", audio:"setenta y ocho", a:"setenta y ocho",
        alts:["78","Setenta y ocho"],
        exp:"\"Setenta y ocho\" = 78. Tens + y + ones for 31+.",
        ctx:"From 31: tens + y + ones, three words. (Exception: 21-29 one word with veinti-.)",
        ex:[{es:"Mi abuela tiene setenta y ocho años.",en:"My grandmother is 78."},{es:"Cuesta cincuenta y tres dólares.",en:"It costs 53 dollars."}],
        vz:"Venezuelan grandparents deeply respected. Family tight. Expect to meet abuela early." },
      { id:"L8-D6", type:"trans_es", q:"My birthday is in March.", a:"Mi cumpleaños es en marzo.",
        alts:["Mi cumpleaños es en Marzo."],
        exp:"\"En marzo\" — months take en. Lowercase always.",
        ctx:"Months always lowercase in Spanish. English capitalizes; Spanish doesn't.",
        ex:[{es:"En enero hace frío.",en:"In January it's cold."},{es:"Vamos a la playa en julio.",en:"We're going to the beach in July."}],
        vz:"\"Diciembre\" huge for Venezuela — Christmas (Navidad) is THE family holiday." },
      { id:"L8-D7", type:"trans_es", q:"How old are you?", a:"¿Cuántos años tienes?",
        alts:["Cuántos años tienes?","¿Qué edad tienes?"],
        exp:"\"¿Cuántos años tienes?\" — literally \"how many years do you have?\"",
        ctx:"Spanish uses TENER for age, not ser. \"Tengo 30 años,\" never \"soy 30.\"",
        ex:[{es:"Tengo treinta años.",en:"I'm 30 years old."},{es:"¿Cuántos años tiene tu mamá?",en:"How old is your mom?"}],
        vz:"Direct but acceptable. \"¿Qué edad tienes?\" slightly more formal." },
      { id:"L8-D8", type:"trans_es", q:"It's 9:30.", a:"Son las nueve y media.",
        alts:["Son las nueve y treinta.","Son las 9 y media."],
        exp:"\"Y media\" = and half.",
        ctx:"Half-past = y media. Quarter-past = y cuarto. Quarter-to = menos cuarto. Universal.",
        ex:[{es:"Son las cinco y media.",en:"It's 5:30."},{es:"Son las nueve menos cuarto.",en:"It's 8:45."}],
        vz:"Common for plans: \"Nos vemos a las nueve y media.\"" },
      { id:"L8-D9", type:"trans_es", q:"Monday", a:"lunes",
        alts:["Lunes"],
        exp:"\"lunes\" — lowercase. Days NOT capitalized in Spanish.",
        ctx:"Days, months, languages, nationalities — all lowercase in Spanish (unless starting sentence).",
        ex:[{es:"El lunes es difícil.",en:"Monday is hard."},{es:"Te veo el lunes.",en:"I'll see you Monday."}],
        vz:"\"El lunes\" with article = \"on Monday.\" Common in scheduling." },
      { id:"L8-D10", type:"trans_es", q:"What time is it?", a:"¿Qué hora es?",
        alts:["Qué hora es?","¿Qué horas son?"],
        exp:"Singular standard form.",
        ctx:"Some LATAM countries say \"¿Qué horas son?\" (plural) — also accepted but less common.",
        ex:[{es:"¿Qué hora es? — Son las tres.",en:"What time? — It's three."},{es:"¿A qué hora?",en:"At what time?"}],
        vz:"\"¿Qué hora es, vale?\" — Venezuelan with vale at end." }
    ]
  },

  // ─── A1 · L9 ─── Palabras Interrogativas ─────────────────────
  { id:"L9", level:"A1", num:9,
    title:"Palabras Interrogativas",
    subtitle:"Question Words — qué, quién, cuándo, dónde, cómo, por qué",
    study:"Spanish question words ALWAYS carry an accent (tilde). QUÉ (what), QUIÉN (who), CUÁNDO (when), DÓNDE (where), CÓMO (how), POR QUÉ (why), CUÁL (which/what), CUÁNTO (how much). Non-accent versions exist as relative pronouns (que, quien, donde) — different role. Question structure: ¿Question word + verb + (subject)? Subject often dropped or placed after verb. Always wrap with ¿ ?",
    tables:[
      { title:"Question Words", rows:[["¿Qué?","What?"],["¿Quién?","Who?"],["¿Cuándo?","When?"],["¿Dónde?","Where?"],["¿Cómo?","How?"],["¿Por qué?","Why?"],["¿Cuál?","Which?"],["¿Cuánto/a/os/as?","How much/many?"]] },
      { title:"Variants", rows:[["¿Quiénes?","Who? (plural)"],["¿Adónde?","To where?"],["¿De dónde?","From where?"],["¿Para qué?","What for?"]] }
    ],
    drills:[
      { id:"L9-D1", type:"fill", q:"___ es tu nombre?", hint:"What", a:"Cuál",
        alts:["cuál","¿Cuál"],
        exp:"\"¿Cuál es tu nombre?\" — Spanish uses cuál before ser + identifying noun. Not qué.",
        ctx:"Tricky: ¿Qué es X? = What is X (definition)? vs ¿Cuál es X? = What is X (selecting)? For names, addresses, numbers — use cuál.",
        ex:[{es:"¿Cuál es tu número?",en:"What's your number?"},{es:"¿Cuál es tu dirección?",en:"What's your address?"}],
        vz:"Casually: \"¿Cómo te llamas?\" more common conversationally." },
      { id:"L9-D2", type:"trans_es", q:"Where do you live?", a:"¿Dónde vives?",
        alts:["Dónde vives?","¿Dónde tú vives?"],
        exp:"\"¿Dónde + verb?\" \"Vives\" already includes \"you,\" no pronoun needed.",
        ctx:"\"Dónde\" with accent = question. \"Donde\" without = relative pronoun. Always include the accent.",
        ex:[{es:"¿Dónde estás?",en:"Where are you?"},{es:"¿Dónde trabajas?",en:"Where do you work?"}],
        vz:"\"¿Dónde vives, chamo?\" — friendly version." },
      { id:"L9-D3", type:"trans_es", q:"Who is she?", a:"¿Quién es ella?",
        alts:["Quién es ella?","¿Quién es?"],
        exp:"\"¿Quién?\" = who (sg). \"Es ella\" — verb before pronoun in questions.",
        ctx:"In questions, subject often AFTER verb. For plural \"who are they?\": ¿Quiénes son ellos?",
        ex:[{es:"¿Quién es esa chica?",en:"Who is that girl?"},{es:"¿Quiénes son ellos?",en:"Who are they?"}],
        vz:"\"¿Quién es esa chama?\" — chama for girl in Venezuelan." },
      { id:"L9-D4", type:"trans_es", q:"When are we going?", a:"¿Cuándo vamos?",
        alts:["Cuándo vamos?","¿Cuándo nos vamos?"],
        exp:"\"¿Cuándo + vamos (ir, nos)?\"",
        ctx:"\"Vamos\" can be \"we go,\" \"let's go,\" or \"we're going\" — context decides.",
        ex:[{es:"¿Cuándo es la fiesta?",en:"When is the party?"},{es:"¿Cuándo vienes?",en:"When are you coming?"}],
        vz:"\"¿Cuándo vamos a Los Roques, mi amor?\" — Venezuelan beach planning with partner." },
      { id:"L9-D5", type:"trans_es", q:"How are you doing?", a:"¿Cómo estás?",
        alts:["Cómo estás?","¿Cómo te va?","¿Qué tal?"],
        exp:"\"¿Cómo estás?\" most common. Or \"¿Cómo te va?\" (how's it going).",
        ctx:"\"¿Cómo estás?\" uses estar (state). \"¿Cómo te va?\" uses ir reflexively.",
        ex:[{es:"¿Cómo estás hoy?",en:"How are you today?"},{es:"¿Cómo te va con el español?",en:"How's Spanish going?"}],
        vz:"In Venezuelan often: \"¿Qué más?\" or \"¿Cómo va la cosa?\" or \"¿Qué hay?\"" },
      { id:"L9-D6", type:"trans_es", q:"Why don't you come?", a:"¿Por qué no vienes?",
        alts:["Por qué no vienes?","¿Por qué tú no vienes?"],
        exp:"\"¿Por qué + no + vienes?\" Two words for why. Don't write as one (porque = because).",
        ctx:"Critical: ¿Por qué? (why? — two words, accent) vs porque (because — one word, no accent). Common mistake.",
        ex:[{es:"¿Por qué estás triste?",en:"Why are you sad?"},{es:"Porque te extraño.",en:"Because I miss you."}],
        vz:"\"¿Por qué no vienes, mi amor?\" — sweet Venezuelan version." },
      { id:"L9-D7", type:"listen", q:"Listen and type.", audio:"¿Cuántos años tiene tu hermana?", a:"¿Cuántos años tiene tu hermana?",
        alts:["Cuántos años tiene tu hermana?","cuántos años tiene tu hermana"],
        exp:"\"How old is your sister?\" Cuántos (m pl) agrees with años.",
        ctx:"Cuánto changes: cuánto (m sg), cuánta (f sg), cuántos (m pl), cuántas (f pl). Match noun.",
        ex:[{es:"¿Cuánto cuesta?",en:"How much does it cost?"},{es:"¿Cuántas personas hay?",en:"How many people are there?"}],
        vz:"Family questions earn points in Venezuelan culture." },
      { id:"L9-D8", type:"trans_es", q:"What do you want to eat?", a:"¿Qué quieres comer?",
        alts:["Qué quieres comer?","¿Qué tú quieres comer?"],
        exp:"\"¿Qué + quieres + comer (inf)?\"",
        ctx:"Querer + infinitive. Two-verb: only first conjugates.",
        ex:[{es:"¿Qué quieres hacer?",en:"What do you want to do?"},{es:"¿Qué quieres tomar?",en:"What do you want to drink?"}],
        vz:"\"¿Qué quieres comer, mi amor?\" — daily Venezuelan question. Probable answer: arepas/pasta/pollo." },
      { id:"L9-D9", type:"trans_es", q:"Where are you from? (informal)", a:"¿De dónde eres?",
        alts:["De dónde eres?","¿De dónde tú eres?"],
        exp:"\"¿De dónde + eres (ser)?\"",
        ctx:"Origin = ser. \"De dónde\" essential first-meeting question.",
        ex:[{es:"¿De dónde eres? — Soy de Texas.",en:"Where are you from? — I'm from Texas."},{es:"Soy de Estados Unidos.",en:"I'm from the US."}],
        vz:"\"Soy de Estados Unidos, pero mi novia es venezolana\" — full origin in one sentence." },
      { id:"L9-D10", type:"trans_es", q:"What's that?", a:"¿Qué es eso?",
        alts:["Qué es eso?","¿Qué es esto?"],
        exp:"\"¿Qué es eso?\" — definition question, uses qué.",
        ctx:"For object identity: ¿Qué es eso/esto/aquello? Eso (that), esto (this), aquello (far that).",
        ex:[{es:"¿Qué es esto?",en:"What is this?"},{es:"¿Qué significa esa palabra?",en:"What does that word mean?"}],
        vz:"\"¿Qué es esto, chamo?\" — point at unfamiliar Venezuelan food. Bonus: \"¿Cómo se come?\"" }
    ]
  },

  // ─── A1 · L10 ─── Adjetivos y Concordancia ───────────────────
  { id:"L10", level:"A1", num:10,
    title:"Adjetivos y Concordancia",
    subtitle:"Adjectives and Agreement",
    study:"Spanish adjectives MUST agree with nouns in gender AND number. Most -O endings change for both: alto/alta/altos/altas. Adjectives ending in -E or consonant only change for number: grande/grandes, fácil/fáciles. Adjectives go AFTER the noun: \"un libro interesante.\" A few go before (bueno/malo) and drop -o before m sg: \"un buen amigo,\" \"un mal día.\"",
    tables:[
      { title:"Agreement Patterns", rows:[["alto (m sg)","tall (m)"],["alta (f sg)","tall (f)"],["altos (m pl)","tall (m pl)"],["altas (f pl)","tall (f pl)"]] },
      { title:"-E or consonant ending", rows:[["grande/grandes","big"],["inteligente/-s","intelligent"],["fácil/fáciles","easy"],["feliz/felices","happy"]] },
      { title:"Drop -o before m sg", rows:[["bueno → buen","good"],["malo → mal","bad"],["primero → primer","first"],["uno → un","a"]] }
    ],
    drills:[
      { id:"L10-D1", type:"trans_es", q:"a tall man", a:"un hombre alto",
        alts:["Un hombre alto"],
        exp:"\"Un hombre alto\" — adjective AFTER noun.",
        ctx:"Most adjectives go AFTER noun in Spanish. Opposite of English. Get used to flipping.",
        ex:[{es:"Es un hombre alto.",en:"He's a tall man."},{es:"Tengo un perro grande.",en:"I have a big dog."}],
        vz:"\"Es un chamo alto\" — Venezuelan flavor." },
      { id:"L10-D2", type:"trans_es", q:"a beautiful house", a:"una casa hermosa",
        alts:["Una casa hermosa","una casa bonita","una casa linda"],
        exp:"\"Una casa hermosa\" — feminine noun → feminine adjective.",
        ctx:"-O adjectives change to -a for feminine. Beauty words: bonita (pretty), linda (lovely), bella (beautiful), hermosa (beautiful).",
        ex:[{es:"Es una casa hermosa.",en:"It's a beautiful house."},{es:"Tienes una sonrisa linda.",en:"You have a lovely smile."}],
        vz:"In Venezuelan: \"está bella\" / \"está bien linda\" daily compliments." },
      { id:"L10-D3", type:"trans_es", q:"intelligent women", a:"mujeres inteligentes",
        alts:["las mujeres inteligentes"],
        exp:"\"Inteligente\" ends in -e, only changes for number.",
        ctx:"-E and consonant endings: no separate m/f forms. Only plural changes: inteligente → inteligentes.",
        ex:[{es:"Son mujeres inteligentes.",en:"They are intelligent women."},{es:"Tengo amigos inteligentes.",en:"I have intelligent friends."}],
        vz:"Compliment culture: Venezuelans appreciate genuine compliments." },
      { id:"L10-D4", type:"fill", q:"Es un ___ amigo. (good)", a:"buen",
        alts:["bueno"],
        exp:"\"Buen\" — bueno DROPS -o before m sg nouns.",
        ctx:"Bueno, malo, primero, tercero, ninguno, uno drop -o before m sg: buen amigo, mal día, primer libro.",
        ex:[{es:"Es un buen amigo.",en:"He's a good friend."},{es:"Tuve un mal día.",en:"I had a bad day."}],
        vz:"\"Es un buen pana\" — Venezuelan flavor." },
      { id:"L10-D5", type:"trans_es", q:"big houses", a:"casas grandes",
        alts:["las casas grandes"],
        exp:"\"Grande\" invariant for gender, only adds -s for plural.",
        ctx:"Grande doesn't change for gender. Same with similar adjectives: simple, importante, interesante.",
        ex:[{es:"Tenemos casas grandes.",en:"We have big houses."},{es:"Son problemas grandes.",en:"They're big problems."}],
        vz:"\"Casas burda de grandes\" — intensifier." },
      { id:"L10-D6", type:"trans_es", q:"happy children", a:"niños felices",
        alts:["los niños felices"],
        exp:"\"Niños felices\" — feliz changes z→c+es: feliz → felices.",
        ctx:"Spelling rule: -z words change to -c before -es. Feliz → felices, lápiz → lápices, vez → veces.",
        ex:[{es:"Somos felices juntos.",en:"We are happy together."},{es:"Niños felices crecen bien.",en:"Happy children grow well."}],
        vz:"\"Estamos felices juntos\" — partner phrase. Or \"estamos chéveres\" Venezuelan-style." },
      { id:"L10-D7", type:"trans_es", q:"my old car", a:"mi carro viejo",
        alts:["Mi carro viejo"],
        exp:"\"Mi carro viejo\" — mi + carro (m) + viejo (m sg).",
        ctx:"\"Mi\" doesn't change for gender (only mi/mis). Noun and adjective match.",
        ex:[{es:"Mi carro es viejo.",en:"My car is old."},{es:"Mi casa es vieja.",en:"My house is old."}],
        vz:"In Venezuelan: \"mi viejo\"/\"mi vieja\" affectionately = dad/mom or wife/girlfriend. Context matters." },
      { id:"L10-D8", type:"listen", q:"Listen and type.", audio:"Las chicas venezolanas son hermosas.", a:"Las chicas venezolanas son hermosas.",
        alts:["las chicas venezolanas son hermosas"],
        exp:"Three-way agreement: Las (f pl) + chicas (f pl) + venezolanas (f pl) + hermosas (f pl).",
        ctx:"Everything agrees: article, noun, nationality adjective, descriptive adjective.",
        ex:[{es:"Las mujeres venezolanas son fuertes.",en:"Venezuelan women are strong."},{es:"Los hombres son altos.",en:"The men are tall."}],
        vz:"Said with confidence to your girlfriend, generally appreciated. Reputation supports it." },
      { id:"L10-D9", type:"trans_es", q:"a young teacher (f)", a:"una maestra joven",
        alts:["Una maestra joven"],
        exp:"\"Joven\" invariant for gender (consonant ending).",
        ctx:"Joven doesn't change for gender. Plural: jóvenes (note accent appears).",
        ex:[{es:"Es una maestra joven.",en:"She's a young teacher."},{es:"Es un médico joven.",en:"He's a young doctor."}],
        vz:"\"Es una chama joven\" — Venezuelan way of saying \"young girl/woman.\"" },
      { id:"L10-D10", type:"trans_es", q:"an interesting book", a:"un libro interesante",
        alts:["Un libro interesante"],
        exp:"\"Interesante\" invariant (-e ending).",
        ctx:"-E adjectives gender-neutral: interesante, importante, fácil. Only change for plural.",
        ex:[{es:"Es un libro interesante.",en:"It's an interesting book."},{es:"Tiene una vida interesante.",en:"He has an interesting life."}],
        vz:"\"Una vida burda chévere\" — really cool life Venezuelan-style." }
    ]
  },

  // ─── A1 · L11 ─── Posesivos ──────────────────────────────────
  { id:"L11", level:"A1", num:11,
    title:"Posesivos",
    subtitle:"Possessives — mi, tu, su, nuestro",
    study:"Possessive adjectives go BEFORE the noun. They agree with the noun (thing owned), not the owner. MI/MIS (my), TU/TUS (your-informal), SU/SUS (his/her/your-formal/their — ambiguous!), NUESTRO/A/OS/AS (our). Only nuestro changes for gender. \"Su\" is contextually ambiguous — clarify with \"de él/ella\" if needed.",
    tables:[
      { title:"Possessives", rows:[["mi / mis","my"],["tu / tus","your (informal)"],["su / sus","his/her/your(formal)/their"],["nuestro/a/os/as","our"]] },
      { title:"Examples", rows:[["mi casa","my house"],["mis casas","my houses"],["nuestra novia","our girlfriend"],["nuestros amigos","our friends"],["sus libros","his/her/their books"]] }
    ],
    drills:[
      { id:"L11-D1", type:"trans_es", q:"my house", a:"mi casa",
        alts:["Mi casa"],
        exp:"\"Mi casa\" — mi (sg) + casa (sg). Mi doesn't change for gender.",
        ctx:"\"Mi\" invariant for gender. Plural: mis. Mi casa, mi libro, mi mamá, mi papá.",
        ex:[{es:"Mi casa es tu casa.",en:"My house is your house."},{es:"Mi familia es importante.",en:"My family is important."}],
        vz:"\"Mi casa es tu casa\" — universal hospitality, even more meaningful in Venezuelan culture." },
      { id:"L11-D2", type:"trans_es", q:"your books (informal)", a:"tus libros",
        alts:["Tus libros"],
        exp:"\"Tus libros\" — tu becomes tus for plural.",
        ctx:"Possessive matches noun's number. Singular noun → tu/mi/su. Plural → tus/mis/sus.",
        ex:[{es:"Tus libros están en la mesa.",en:"Your books are on the table."},{es:"Tus amigos vienen.",en:"Your friends are coming."}],
        vz:"\"Tus panas vienen\" — Venezuelan flavor." },
      { id:"L11-D3", type:"trans_es", q:"his car", a:"su carro",
        alts:["Su carro"],
        exp:"\"Su carro\" — su = his/her/your-formal/their. Context disambiguates.",
        ctx:"Most ambiguous possessive. To clarify: \"el carro de él\" (his), \"el carro de ella\" (her).",
        ex:[{es:"Su carro es nuevo.",en:"His/Her/Their car is new."},{es:"Su mamá viene.",en:"His/Her mom is coming."}],
        vz:"For clarity casually: \"la mamita de él\" — diminutive Venezuelan-style." },
      { id:"L11-D4", type:"trans_es", q:"our friends", a:"nuestros amigos",
        alts:["Nuestros amigos"],
        exp:"\"Nuestros\" — our (m pl). Nuestro is the only possessive changing for gender.",
        ctx:"Nuestro forms: nuestro (m sg), nuestra (f sg), nuestros (m pl), nuestras (f pl).",
        ex:[{es:"Nuestros amigos son geniales.",en:"Our friends are great."},{es:"Nuestra casa es pequeña.",en:"Our house is small."}],
        vz:"Venezuelan culture is family-centric. \"Nuestra familia binacional\" — common diaspora phrase." },
      { id:"L11-D5", type:"trans_es", q:"her sister", a:"su hermana",
        alts:["Su hermana","la hermana de ella"],
        exp:"\"Su hermana\" — su + hermana (sg).",
        ctx:"Su agrees with what's owned, not the owner. Works regardless of owner's gender.",
        ex:[{es:"Su hermana vive en Caracas.",en:"Her sister lives in Caracas."},{es:"Sus hermanas son simpáticas.",en:"Her sisters are friendly."}],
        vz:"Many Venezuelans have family across multiple countries due to migration." },
      { id:"L11-D6", type:"trans_es", q:"my parents", a:"mis padres",
        alts:["Mis padres","mis papás"],
        exp:"\"Mis padres\" / \"mis papás\" — both work.",
        ctx:"\"Padres\" defaults to \"parents.\" \"Mis papás\" (mom + dad) common informally.",
        ex:[{es:"Mis padres son americanos.",en:"My parents are American."},{es:"Mis papás viven en Texas.",en:"My parents live in Texas."}],
        vz:"In Venezuelan: \"mis viejos\" affectionately = my parents (lit. \"my old ones\")." },
      { id:"L11-D7", type:"trans_es", q:"our daughter", a:"nuestra hija",
        alts:["Nuestra hija"],
        exp:"\"Nuestra hija\" — nuestra (f sg) matches feminine.",
        ctx:"Nuestra hija (daughter), nuestro hijo (son), nuestras hijas (daughters), nuestros hijos (sons or mixed children).",
        ex:[{es:"Nuestra hija tiene cinco años.",en:"Our daughter is 5."},{es:"Nuestros hijos son maravillosos.",en:"Our children are wonderful."}],
        vz:"Family talk frequent. \"Hijos\" can mean \"children\" or \"sons\" by context." },
      { id:"L11-D8", type:"listen", q:"Listen and type.", audio:"Mi novia es de Caracas y su familia vive allá.", a:"Mi novia es de Caracas y su familia vive allá.",
        alts:["mi novia es de caracas y su familia vive allá"],
        exp:"\"My girlfriend is from Caracas and her family lives there.\" Mi + su.",
        ctx:"Common diaspora sentence. Mi novia + su familia — two relationships, two possessives.",
        ex:[{es:"Mi mamá vive aquí; su mamá vive allá.",en:"My mom lives here; his/her mom lives there."},{es:"Tu casa es nueva; mi casa es vieja.",en:"Your house is new; mine is old."}],
        vz:"Very common Venezuelan-American scenario. Caracas frequent answer for family origin." },
      { id:"L11-D9", type:"trans_es", q:"their houses", a:"sus casas",
        alts:["Sus casas"],
        exp:"\"Sus casas\" — sus (pl) + plural noun.",
        ctx:"Sus = their/his/her/your(formal). When things owned are plural, use sus.",
        ex:[{es:"Sus casas son grandes.",en:"Their houses are big."},{es:"Sus padres son simpáticos.",en:"Their parents are friendly."}],
        vz:"Venezuelan diaspora often maintains houses in two countries." },
      { id:"L11-D10", type:"trans_es", q:"my Venezuelan girlfriend", a:"mi novia venezolana",
        alts:["Mi novia venezolana"],
        exp:"\"Mi novia venezolana\" — mi + novia (f sg) + venezolana (f sg).",
        ctx:"Possessive + noun + adjective. All feminine singular agreement.",
        ex:[{es:"Mi novia venezolana se llama Ana.",en:"My Venezuelan girlfriend is named Ana."},{es:"Mi mejor amigo es venezolano.",en:"My best friend is Venezuelan."}],
        vz:"Add: \"y la amo full/burda\" — Venezuelan intensifiers." }
    ]
  },

  // ─── A1 · L12 ─── Vocabulario Esencial ───────────────────────
  { id:"L12", level:"A1", num:12,
    title:"Vocabulario Esencial",
    subtitle:"Essential Vocabulary — Family, Food, Body",
    study:"Three foundational vocabulary domains. FAMILY: mamá, papá, hermano/a, hijo/a, abuelo/a, tío/a, primo/a. FOOD: arepa (Venezuelan corn cake), pan, agua, café, pollo, carne, arroz, caraotas (Venezuelan beans), huevo, queso, leche. BODY: cabeza, ojo, boca, mano, pie, brazo, pierna, corazón. These appear in every conversation.",
    tables:[
      { title:"Family", rows:[["mamá / madre","mom"],["papá / padre","dad"],["hermano/a","brother/sister"],["hijo/a","son/daughter"],["abuelo/a","grandparent"],["tío/a","uncle/aunt"]] },
      { title:"Food", rows:[["pan","bread"],["agua","water"],["café","coffee"],["pollo","chicken"],["arroz","rice"],["queso","cheese"]] },
      { title:"Body", rows:[["cabeza","head"],["mano","hand"],["pie","foot"],["ojo","eye"],["corazón","heart"]] }
    ],
    drills:[
      { id:"L12-D1", type:"trans_es", q:"mom", a:"mamá",
        alts:["la mamá","Mamá","madre","la madre"],
        exp:"\"Mamá\" — informal, daily. \"Madre\" more formal.",
        ctx:"Casual speech: mamá dominates. Madre in formal contexts or idiomatic phrases.",
        ex:[{es:"Mi mamá es venezolana.",en:"My mom is Venezuelan."},{es:"¿Cómo está tu mamá?",en:"How is your mom?"}],
        vz:"In Venezuelan: \"mami,\" \"mamita,\" \"mi vieja\" affectionately." },
      { id:"L12-D2", type:"trans_es", q:"my brother", a:"mi hermano",
        alts:["Mi hermano"],
        exp:"\"Mi hermano\" — sister: mi hermana.",
        ctx:"\"Hermano\" / \"hermana.\" \"Mano\" (short for hermano) used as \"bro\" between male friends.",
        ex:[{es:"Mi hermano vive en Texas.",en:"My brother lives in Texas."},{es:"Tengo dos hermanas.",en:"I have two sisters."}],
        vz:"\"Mano, ¿qué tal?\" = Bro, what's up?" },
      { id:"L12-D3", type:"trans_es", q:"the bread", a:"el pan",
        alts:["El pan"],
        exp:"\"El pan\" — masculine despite -n ending.",
        ctx:"Most -n consonant words still masculine. Common food masculines: el pan, el café, el queso, el arroz, el pollo.",
        ex:[{es:"Quiero pan, por favor.",en:"I want bread, please."},{es:"El pan está fresco.",en:"The bread is fresh."}],
        vz:"In Venezuela: \"pan canilla\" (small French-style), \"pan dulce,\" \"pan andino\" — try them all." },
      { id:"L12-D4", type:"trans_es", q:"chicken", a:"pollo",
        alts:["el pollo","Pollo"],
        exp:"\"Pollo\" — masculine, -o ending.",
        ctx:"\"Pollo\" — chicken meat. Live: la gallina (hen), el gallo (rooster).",
        ex:[{es:"Como pollo todos los días.",en:"I eat chicken every day."},{es:"Pollo asado es delicioso.",en:"Roasted chicken is delicious."}],
        vz:"In Venezuela: \"pollo en brasas\" (rotisserie chicken) iconic. Restaurants on every block." },
      { id:"L12-D5", type:"trans_es", q:"the head", a:"la cabeza",
        alts:["La cabeza"],
        exp:"\"La cabeza\" — feminine.",
        ctx:"Body parts use definite article when speaking about your own. \"Me duele la cabeza\" — implied possessive from verb.",
        ex:[{es:"Me duele la cabeza.",en:"My head hurts."},{es:"Tengo dolor de cabeza.",en:"I have a headache."}],
        vz:"\"Me duele burda la cabeza\" — Venezuelan-style headache complaint." },
      { id:"L12-D6", type:"trans_es", q:"the hands", a:"las manos",
        alts:["Las manos"],
        exp:"\"Las manos\" — \"mano\" is FEMININE despite -o ending.",
        ctx:"Famous gender exception: -o ending but feminine. Other -o feminines: la foto, la moto.",
        ex:[{es:"Las manos están frías.",en:"The hands are cold."},{es:"Lávate las manos.",en:"Wash your hands."}],
        vz:"\"Lávate las manos\" — universal mom command." },
      { id:"L12-D7", type:"vz_recall", q:"Venezuelan word for \"beans\" (different from most LATAM)?", a:"caraotas",
        alts:["Caraotas","las caraotas"],
        exp:"\"Caraotas\" — uniquely Venezuelan. Most LATAM uses \"frijoles.\"",
        ctx:"Mexico/Central America = frijoles. Caribbean = different terms. Venezuela: caraotas. Puerto Rico/DR: habichuelas.",
        ex:[{es:"Las caraotas negras son típicas en Venezuela.",en:"Black beans are typical in Venezuela."},{es:"Quiero arroz con caraotas.",en:"I want rice with beans."}],
        vz:"Caraotas + arroz + carne mechada + tajadas = pabellón criollo, the Venezuelan national dish. Learn this!" },
      { id:"L12-D8", type:"trans_es", q:"the heart", a:"el corazón",
        alts:["El corazón"],
        exp:"\"El corazón\" — masculine, accent on ó.",
        ctx:"Last syllable stress, hence tilde. Used literally and as endearment (\"mi corazón\").",
        ex:[{es:"Mi corazón es tuyo.",en:"My heart is yours."},{es:"Tienes buen corazón.",en:"You have a good heart."}],
        vz:"\"Mi corazón\" / \"corazón\" — top Venezuelan term of endearment." },
      { id:"L12-D9", type:"listen", q:"Listen and type.", audio:"Mi familia y yo comemos arepas para el desayuno.", a:"Mi familia y yo comemos arepas para el desayuno.",
        alts:["mi familia y yo comemos arepas para el desayuno"],
        exp:"Family + food + meal vocabulary in one sentence.",
        ctx:"\"Para el desayuno\" — for breakfast. Other meals: el almuerzo (lunch), la cena (dinner).",
        ex:[{es:"Comemos arepas en el desayuno.",en:"We eat arepas at breakfast."},{es:"Cenamos a las ocho.",en:"We have dinner at 8."}],
        vz:"Arepas at any meal — heart of Venezuelan food culture. Especially breakfast." },
      { id:"L12-D10", type:"trans_es", q:"my grandmother", a:"mi abuela",
        alts:["Mi abuela","mi abuelita"],
        exp:"\"Mi abuela\" formal. \"Mi abuelita\" affectionate diminutive.",
        ctx:"Diminutives express warmth. Abuelita more affectionate than abuela. Same with mami/mamita, papi/papito.",
        ex:[{es:"Mi abuela vive en Caracas.",en:"My grandma lives in Caracas."},{es:"Mi abuelita cocina muy bien.",en:"My grandma cooks very well."}],
        vz:"Venezuelan abuelas central — many raise grandchildren when parents work. \"Crié con mi abuelita\" common." }
    ]
  }

  // ═══════════════════════════════════════════════════════════════
  // FUTURE LEVELS (A2, B1, B2, C1, C2) APPEND BELOW
  // Marker: ---NEXT_LEVEL_INSERT---
  // ═══════════════════════════════════════════════════════════════

];

// ═══════════════════════════════════════════════════════════════
// VENEZUELAN TRACK — empty for now, will populate Vz1-Vz5 next
// ═══════════════════════════════════════════════════════════════
window.CURRICULUM.VZ_LESSONS = [
  // ---NEXT_VZ_INSERT---
];
